### ISSUE TITLE
error for filter_reads when qsub jobs

### ISSUE THREAD

**Issue by zhaoc1** [sunbeam-labs/sunbeam#114]
When I qsub `all_decontam` to respublica, I got the following error messages from `filter_reads` rule:

"Error occurred during initialization of VM
Cannot create VM thread. Out of system resources."

After googling the error message, this seems to be a java version issue. 

My experience with respublica  is that it doesn't allowing passing the `LD_LIBRARY_PATH` for security issue, and this will cause error when the local java version is different from the conda environment java version. One way to walk around this, thanks to @ressy, is to explicitly setting `LD_LIBRARY_PATH="$CONDA_PREFIX/lib64"`. However, I am not sure whether this is the reason for our error message.

Since we are filtering reads based by ids, shall we just add a python script to sunbeamlib to do the work?

**Comment by eclarke** [comment]
Fixed in #123
