### ISSUE TITLE
mask_low_complexity failed

### ISSUE THREAD

**Issue by guanzhidao** [sunbeam-labs/sunbeam#116]
Error in rule mask_low_complexity:
    jobid: 0
    output: /home/guanxian/sunbeam_output/qc/masked/D5_R2.fastq.gz

RuleException:
KeyError in line 92 of /gpfs/fs02/home/guanxian/sunbeam/rules/qc/qc.rules:
'mask_low_complexity'
  File "/gpfs/fs02/home/guanxian/sunbeam/rules/qc/qc.rules", line 92, in __rule_mask_low_complexity
  File "/home/guanxian/miniconda3/envs/sunbeam/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /gpfs/fs02/home/guanxian/sunbeam/.snakemake/log/2018-03-01T135544.313766.snakemake.log
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /gpfs/fs02/home/guanxian/sunbeam/.snakemake/log/2018-03-01T135417.663390.snakemake.log

**Comment by eclarke** [comment]
Can you post your config file here? I think you're missing a key under `qc`:

```yaml
qc:
   mask_low_complexity: true
```

Sorry this hasn't been documented yet (working on it!) but you can update an existing config file for a new version of Sunbeam by running 
```bash
sunbeam_init [project_name] > new_project_config.yml
sunbeam_mod_config --old_config old_project_config.yml --config new_project_config.yml > new_project_config.yml
```

This will ensure create a new version of the config file and update any values in it from your old config file.

Please let me know if the error persists!

**Comment by guanzhidao** [comment]
Fixed! Thanks!
