### ISSUE TITLE
version `GLIBC_2.18' not found (required by kz)

### ISSUE THREAD

**Issue by zhaoc1** [sunbeam-labs/sunbeam#125]
When I run the testing script from the stable branch as suggested in the tutorial, I got an error when running rules `remove_low_complexity`. I attached the error log file [test_all.err.txt](https://github.com/sunbeam-labs/sunbeam/files/1849289/test_all.err.txt), related to #123 

Following up on 20180328:
I figured out this is a issue of `kcomplexity` conda package. So I `conda remove kcomplexity` and install the kcomplesity from the [git repo](https://github.com/eclarke/komplexity), as a temporary walk around.

And [here](https://github.com/rust-lang-nursery/rustup.rs/issues/1339) is the related issue for rust.

**Comment by louiejtaylor** [comment]
Given the fact that installing v0.3.0 from github fixed the issue and runs the tests fine (per our conversation), I think probably it'd be best to update the version in conda (v0.2.1) to the current version and see if that fixes things. I don't have privileges for the bushman conda channel but someone who does can add the new version using the updated [recipe](https://github.com/louiejtaylor/kz_conda)

**Comment by eclarke** [comment]
Yeah I can do that as soon as I get access to a terminal. Thanks for debugging!

**Comment by eclarke** [comment]
Sorry for the delay with this. I don't think that the manual install you mentioned will fix it- this seems to be an issue with the Rust binaries linking to a version of glibc by default that's not available for some deployments. I found a way to make the rust binaries self-contained (i.e. static) by replacing the glibc dependency with an alternative libc called `musl`.

However, this makes Conda deployment more complicated for reasons I won't go into here. What I'm currently trying is to make Travis build static binaries for komplexity on every release, which will then be uploaded to the conda channel. 

Stay tuned!
