### ISSUE TITLE
add --maxseqlength to vserach command in final_contigs

### ISSUE THREAD

**Issue by zhaoc1** [sunbeam-labs/sunbeam#126]
As suggested in the title, the default `--maxseqlength` of vserach 50,000, and we don't want to filter those long contigs out. Add `--maxseqlength` 10000000000.

**Comment by eclarke** [comment]
Is there a way to negate the max length altogether? Maybe -1?

**Comment by zhaoc1** [comment]
No problem. I will do it over this weekend (right now in nanopore world) LOL
