### ISSUE TITLE
Reads numbers are different in read1 and read2 after Trimmomatic step

### ISSUE THREAD

**Issue by guanzhidao** [sunbeam-labs/sunbeam#131]
In some samples, Rule trimmomatic_unpaired may generate XX_1.fastq.gz which have different reads number from the XX_2.fastq.gz which may be generated by Rule trimmomatic_paired? BWA cannot map them to host genome.
After removing Rule trimmomatic_unpaired, this problem was fixed.

**Comment by eclarke** [comment]
Thanks @guanzhidao, I'll try to get a fix out for this soon!

**Comment by eclarke** [comment]
This should be fixed in #134
