### ISSUE TITLE
Create Anvi'o extension for sunbeam

### ISSUE THREAD

**Issue by eclarke** [sunbeam-labs/sunbeam#133]

**Comment by zhaoc1** [comment]
Hi @eclarke I just did the first commit to sbx_anvio extension. I only did the testing locally on non-empty contigs.fa as input. Right now `all_anvio_svg` doesn't work if the contig file is empty. Can you please take a try at it, and let me know what else you want me to add? Thanks

**Comment by eclarke** [comment]
Great! I'll take a look at it tomorrow- that was a fast turnaround!
