### ISSUE TITLE
Extensions only load when running within sunbeam directory

### ISSUE THREAD

**Issue by ressy** [sunbeam-labs/sunbeam#138]
Sunbeam loads extensions with this call in the Snakefile:

    sbxs = list(listfiles("extensions/{sbx_folder}/{sbx}.rules"))

But that means you have to execute the sunbeam command within the sunbeam directory; calls from within (for example) a separate project directory fail to find the extensions since the working directory doesn't contain the extensions.

How about using the SUNBEAM_DIR environment variable that's already in use elsewhere to find the sunbeam directory at runtime?  Something like this (but probably written to be safer), maybe:

    sbxs = list(listfiles(os.getenv("SUNBEAM_DIR") + "/extensions/{sbx_folder}/{sbx}.rules"))

**Comment by eclarke** [comment]
You are precisely one day too late! I just fixed this, using almost exactly the solution you provide here :D 

Great minds think alike, I guess!
