### ISSUE TITLE
Default .fastq.gz file format?

### ISSUE THREAD

**Issue by kevinmcc21** [sunbeam-labs/sunbeam#146]
I tried running sunbeam init and was told my file names were not in the proper format.  They seemed to be fine though, all of them were in this basic format:
TA_009_S211_L003_R2_001.fastq.gz
I specified --format "{sample}_R{rp}_001.fastq.gz" which got it to work.
Shouldn't this be the default format it looks for?  I copied/pasted the one from this page:
http://sunbeam.readthedocs.io/en/latest/usage.html

**Comment by eclarke** [comment]
Yeah, it should have been able to guess that. The exact error message here would help- can you provide it and a listing of a few more of your files?

**Comment by kevinmcc21** [comment]
(sunbeam) kevin@microb191:~/projects/micu[15:54] sunbeam init micu --force --data_fp /home/kevin/projects/micu/fastq/
New config file written to /home/kevin/projects/micu/micu/sunbeam_config.yml
Guessing sample name format from files in /home/kevin/projects/micu/fastq...
  Best guess: {sample}_001.fastq.gz
Error: assuming paired-end reads, but could not find mates. Specify --single-end if not paired-end, or provide sample name format using --format.
  Reason: missing mate pairs for samples: TA_008_S210_L003_R2, ETA_079_S168_L001_R2, ETA_081_S213_L001_R1, SS_021_S33_L002_R1

There are > 1200 files, but here are a few more:
ETA_008_S94_L003_R1_001.fastq.gz
ETA_053_S141_L003_R1_001.fastq.gz
H2O_5_S58_L003_R1_001.fastq.gz
SS_027_S40_L002_R1_001.fastq.gz
TA_005_S173_L002_R1_001.fastq.gz
