### ISSUE TITLE
Use conda environment variables for Illumina adapters

### ISSUE THREAD

**Issue by louiejtaylor** [sunbeam-labs/sunbeam#150]

**Comment by eclarke** [comment]
To clarify, right now we use absolute paths to reference Illumina adaptors for Trimmomatic. It would be more flexible if we used the $CONDA_ENV environment variables in the config file instead. @zhaoc1 would you be able to tackle this?

**Comment by ressy** [comment]
>  the $CONDA_ENV environment variables

$CONDA_PREFIX, I think?

**Comment by eclarke** [comment]
Yes, thanks!

**Comment by louiejtaylor** [comment]
Not sure if this is relevant here or should be opened as a new issue. Just was debugging #157 and got a weird error when I got to `sunbeam run`:

        ValueError in line 56 of /scratch001/sunbeam-stable/Snakefile:
    For key 'adapter_fp': path '/home/louis/miniconda2/envs/sunbeam/share/trimmomatic/adapters/NexteraPE-PE.fa' does not exist

Turns out that apparently the trimmomatic folder in `envs/sunbeam/share` is now named like: `trimmomatic-0.38-0`. Changing that in the config file worked, but I think it should probably be fixed in the default.

**Comment by eclarke** [comment]
Haha, yeah, you're absolutely right but about 30m late :D 

I just pushed efe7f01ef24f5d48fb82ebcdff55318c85caf32b which locked trimmomatic to v0.36- try reinstalling from `dev`

**Comment by ressy** [comment]
Tracing backwards from the CONDA_FP placeholder in the default config to `get_conda_prefix()` in init.py that fills in the placeholder, it's already using `os.environ.get("CONDA_PREFIX")`, so I think we're all set, right?

**Comment by ressy** [comment]
Strike that, on re-reading I think *now* I get the idea-- we should leave the conda path templated in the live config file, so the full path for adapter_fp is resolved each time the file is loaded (as opposed to figuring out the path at init-time and then hardcoding that absolute path into the file as a plain string).  Does that sound right?  I could try to tackle this and #152 in one go as a set of related config file topics.
