### ISSUE TITLE
sunbeam config update fails

### ISSUE THREAD

**Issue by ressy** [sunbeam-labs/sunbeam#152]
Running `sunbeam config update configfile.yml` fails for me with this error:

    Traceback (most recent call last):
      File "/home/ancon/miniconda3/envs/ips/bin/sunbeam", line 11, in <module>
        load_entry_point('sunbeam==1.0.2.dev23+gc1b811d.d20180523', 'console_scripts', 'sunbeam')()
      File "/home/ancon/miniconda3/envs/ips/lib/python3.6/site-packages/sunbeamlib/scripts/command.py", line 42, in main
        Config(remaining)
      File "/home/ancon/miniconda3/envs/ips/lib/python3.6/site-packages/sunbeamlib/scripts/_config.py", line 69, in main
        args.func(args)
      File "/home/ancon/miniconda3/envs/ips/lib/python3.6/site-packages/sunbeamlib/scripts/_config.py", line 83, in update
        conda_fp = config._find_conda_fp(),
    AttributeError: module 'sunbeamlib.config' has no attribute '_find_conda_fp'

scripts/_config.py is trying to do this:

    new_config = config.new(
        conda_fp = config._find_conda_fp(),
        project_fp = old_config.get('all', {}).get('version', ''),
        template = args.template)

And it's right, there's currently no _find_conda_fp function in the config module, following the cleanup in ae5600bc95572ee43025f25345cf36ea4514d22b.  Did we lose functionality there?  (I should mention, I have c1b811d97588d5cc10d7f8206deb2395ec9762f8 checked out locally while I look at this, but I don't think any of these files have changed in the meantime.)

**Comment by eclarke** [comment]
The only reason we need `conda_fp` is to point to the Trimmomatic resources, which can and should be resolved through the use of environment variables as described in #150. Fixing that issue should allow us to remove the offending lines here.

**Comment by eclarke** [comment]
So... we still haven't fixed this! Just commenting to re-up this. I'll work on it
