### ISSUE TITLE
Behavior of empty paths in configs should be clarified

### ISSUE THREAD

**Issue by ressy** [sunbeam-labs/sunbeam#153]
Currently an empty string for directory paths, such as the several used in the default config file, will result in the working directory itself being used for that section's path.  If the relevant files don't exist at the top level it won't matter, but if any files happen to match, this can cause unintuitive behavior.  (For example files ending in .fasta will be picked up and used for the mapping step even if that config section is left with its default blank entries.)

I can think of a few ways we could clarify this and allow an explicitly-disabled config section:

 * Switch to using `null` in the config file for paths that should not be used at all.  [This will map to None in Python](http://yaml.org/spec/1.2/spec.html#id2803362).  We'd then have to handle that in Snakefile/targets.
 * Explicitly skip targets for the relevant section if any empty string is given for the path.  We'd still have to catch that in Snakefile/targets but then we don't have to change the current YAML.

Any opinions?

**Comment by eclarke** [comment]
I think it's reasonable to use the second option, as it's probably what most people expect to happen by leaving it blank. We can make the path resolver function return None if it's blank, but then we need to be pretty thorough in handling None-type errors downstream, as those create pretty unintuitive error messages.

**Comment by ressy** [comment]
That makes sense.  One way to do it that's a little kludgy but requires the least change to the existing code would be to catch this case when defining paths in the Snakefile (after they've already been made absolute).

Like, in place of:

    HostGenomeFiles = [f for f in Cfg['qc']['host_fp'].glob('*.fasta')]

We'd have:

    if str(Cfg['qc']['host_fp']) == str(Cfg['all']['root']):
        HostGenomeFiles = []
    else:
        HostGenomeFiles = [f for f in Cfg['qc']['host_fp'].glob('*.fasta')]

And then nothing else (like validate_paths in the config module) would need to change.  I think this issue only really even comes up for qc and mapping, so maybe that's OK?

That does ignore one potential situation where Cfg['all']['root'] wasn't defined in the first place, and then check_config defaults to using the current working directory internally.  We could modify check_config slightly to add `new_cfg['all']['root'] = root` so that there's always a root Path object defined in the loaded config, and then we could just do `if Cfg['qc']['host_fp'] == Cfg['all']['root']` in the above, and compare the two Path objects.

**Comment by ressy** [comment]
I'm working on a fix using that last idea (`new_cfg['all']['root'] = root` followed by `if Cfg['qc']['host_fp'] == Cfg['all']['root']` etc.) but setting up a failing test to commit first since it's more than a trivial change.

**Comment by ressy** [comment]
Forgot to reference the issue in the commit, but the should-be-fixed test is running on db38cb3984e713809443010ded77a7ace3300b94 now.

**Comment by eclarke** [comment]
Fixed in #164
