### ISSUE TITLE
all_qc step isn't called by default

### ISSUE THREAD

**Issue by kevinmcc21** [sunbeam-labs/sunbeam#155]
After running sunbeam init, my sunbeam run command fails when snakemake tries to find cutadapt log files.  These files are required by rule "preprocess_report" in reports.rules and created by rule "trimmomatic_unpaired" in qc.rules.

When I specify sunbeam run the "all_qc" rule, it works and creates these files, and when I subsequently run sunbeam without a rule, it is able to find the missing files.  But for some reason, it can't find the log files when I run it from scratch.

As was the case with a prior bug, I have lost the console output to the void... I'm tempted to file "console output not saved to log file" as another bug, but that just feels obnoxious. :)

**Comment by ressy** [comment]
Aha, snakemake version was 3.13.0 rather than 4.8.1.  I expect this will work as expected with the newer snakemake.
