### ISSUE TITLE
Trimmomatic-related path does not exist in test

### ISSUE THREAD

**Issue by gputzel** [sunbeam-labs/sunbeam#156]
After installation I run

`tests/run_tests.bash -e sunbeam`

and get:

    Running setup... \u2714
    Running build_test_data... \u2714
    Running test_all... 
    Failed command error output:
    Found extension sbx_test in folder sbx_test
    ValueError in line 56 of /scratch001/myusername/sunbeam-stable/Snakefile:
    For key 'adapter_fp': path '/home/myusername/miniconda3/envs/sunbeam/share/trimmomatic/adapters/NexteraPE-PE.fa' does not exist
      File "/scratch001/myusername/sunbeam-stable/Snakefile", line 56, in <module>
      File "/scratch001/myusername/sunbeam-stable/sunbeamlib/config.py", line 67, in check_config
      File "/scratch001/myusername/sunbeam-stable/sunbeamlib/config.py", line 45, in validate_paths
    x (log: /tmp/tmp.W1a9WqUxW2/test_all.[out/err])
    -- TESTS FAILED --

The issue seems to be that it can't find `miniconda3/envs/sunbeam/share/trimmomatic/adapters/NexteraPE-PE.fa`. I don't have the directory `trimmomatic`, but I do have `~/miniconda3/envs/sunbeam/share/trimmomatic-0.38-0/`.

**Comment by eclarke** [comment]
Thanks for the bug report. It may be that trimmomatic has changed directories between versions. I’ll investigate and let you know when I have a patch.

**Comment by eclarke** [comment]
The `dev` branch should now have Trimmomatic locked to the correct version. Try reinstalling from `dev` and let me know if the problem continues.
