### ISSUE TITLE
need a flag when megahit failed 

### ISSUE THREAD

**Issue by zhaoc1** [sunbeam-labs/sunbeam#167]
Sometimes, the assembly failed due to technical reasons, e.g the cluster, and we should add a flag for cases like this. 

This is only for marking purpose. I will solve this sometime next week.

**Comment by eclarke** [comment]
@zhaoc1 is this done? I see a flag in the megahit code, is it the one you're referring to?

**Comment by zhaoc1** [comment]
Yes this is done. However the user need to check the log file if they want to know the exit code from megahit.

**Comment by ressy** [comment]
Should we possibly just move the `touch {output}` line for those two rules into the `[ $exitcode -eq 255 ]` case that handles empty contigs?  That way it'll fail to produce any output for any other error megahit has and you'll see the failure directly during the Snakemake run, but you can still use the retries/keep-going features if you want to.  Does that make sense?
