### ISSUE TITLE
sunbeam init --single_end should improve guessing

### ISSUE THREAD

**Issue by louiejtaylor** [sunbeam-labs/sunbeam#168]
Trying `sunbeam init` on a single-end dataset from SRA, and it seems that Sunbeam struggles to guess single-end filenames:

    New config file written to [fp]/sunbeam_config.yml
    Guessing sample name format from files in [fp]/download...
      Best guess: {sample}{sample}.fastq.gz
    Error: could not create sample list. Specify correct sample filename format using --format.
      Reason: no samples matching the given format found.

Admittedly this can be mitigated by me not being lazy and passing `--format`. But hopefully it's an easy fix.

**Comment by eclarke** [comment]
What do the file names actually look like? What would the correct sample format be?

**Comment by louiejtaylor** [comment]
The sample names are straight from SRA, so like:

SRA33467347.fastq.gz
SRA38345435.fastq.gz

It would just be "{sample}.fastq.gz" (which works fine if you pass it with `--pattern`)

**Comment by ressy** [comment]
We can’t reproduce this problem anymore.
