### ISSUE TITLE
Mentioning Databases for workflow

### ISSUE THREAD

**Issue by Lswhiteh** [sunbeam-labs/sunbeam#169]
Not as much an issue as a suggestion, but it would be helpful to have in the documentation somewhere the easiest way to download genome and kraken databases.  [This repo](https://github.com/zhaoc1/sunbeam_databases) was especially helpful, but just reading over the docs there's not a good sense of how to do that for someone approaching metagenomic pipelines without much experience (including myself).

**Comment by louiejtaylor** [comment]
Thank you for the suggestion! This is a great idea. The documentation should help people set up databases that Sunbeam can use, or at the very least point to resources that do.

**Comment by louiejtaylor** [comment]
We've added some callouts to resources in the documentation for building databases (as well as a callout to this helpful repo from @zhaoc1!). Thanks again for the suggestion!
