### ISSUE TITLE
`sunbeam get` doesn't write the correct samples.csv path in the .yml if both paired and unpaired samples are found 

### ISSUE THREAD

**Issue by louiejtaylor** [sunbeam-labs/sunbeam#176]
This is my fault and I will fix it

**Comment by louiejtaylor** [comment]
Similar issue--"sunbeam get" didn't create the "sunbeam_output" folder for me just now on PMACS. Which is weird because it ran fine before...

**Comment by ressy** [comment]
Thanks for stress-testing the get features some more, Louis.  (I stuck myself in here too as a reminder since I'm working on refactoring init/get together.)
