### ISSUE TITLE
samtools cannot find libcrypto.so.1.0.0

### ISSUE THREAD

**Issue by louiejtaylor** [sunbeam-labs/sunbeam#181]
This is a solved problem, but I wanted to archive it here in case anyone has seen this or had/will have the same issue in the future. Had kind of a weird issue working on the cluster that I hadn't seen before. In the `align_to_host` rule, I kept getting errors that boiled down to this:

    samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

Fortunately, the Google oracle led me to someone with the [same issue](https://github.com/bioconda/bioconda-recipes/issues/12100), and the solution there worked for me. Remove the sunbeam environment, then re-run `install.sh` after putting the following into ~/.condarc:

    channels:
      - conda-forge
      - bioconda
      - eclarke
      - louiejtaylor
      - defaults

Since this is a solved issue, I'll close it soon--wanted to bring it to y'alls attention just in case.

**Comment by mheskett** [comment]
Still an issue and not solved. When I install Samtools () it breaks BCFtools giving the libcrypto error. When I uninstall samtools I can use bcftools. Even using the openssl=1.0 trick, and changing .condarc did not work

**Comment by eclarke** [comment]
This is an issue with Bioconda, not Sunbeam. Please see these links:
- https://github.com/bioconda/bioconda-recipes/issues/12100
- https://github.com/bioconda/bioconda-recipes/issues/13958

In general, if you find you are having issues with conda dependencies breaking each other, it is a good idea to simply install them into their own separate conda environments and switch environments as necessary.

**Comment by mheskett** [comment]
OK thanks! So in a shell script (bioinformatics pipeline) you can change
environments before each step?

**Comment by louiejtaylor** [comment]
Yes, that is definitely possible (and we do use isolated environments for some of our extensions). For this particular issue, Jesse has done a very [deep dive](https://github.com/sunbeam-labs/sunbeam/issues/192#issuecomment-478137643) into what causes this particular error and how to fix it--see [this comment](https://github.com/sunbeam-labs/sunbeam/issues/192#issuecomment-478151276) in particular for a solution to this particular problem. @ressy you're the best!

**Comment by ressy** [comment]
Thanks Louis!  Yes @mheskett you can use isolated environments for individual rules via snakemake, or if you're just working directly with conda packages yourself, just use separate environments for the different projects like Erik mentioned.

Are you running into these problems while working within Sunbeam (or with a Sunbeam extension)?  Or  having trouble with these conda packages in general?  If it's the latter I'd second what @eclarke said and check out those bioconda issues (bioconda/bioconda-recipes#12100 and bioconda/bioconda-recipes#13958) since that'll be more specific to the (bio)conda-related problem.

**Comment by mheskett** [comment]
excellent thanks for the response

**Comment by zhypan** [comment]
I add a independent enviroment to snakemake yaml file, then it work. 

 channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - samtools
  - openssl=1.0
