### ISSUE TITLE
Sunbeam / Snakemake and slurm

### ISSUE THREAD

**Issue by Thomieh73** [sunbeam-labs/sunbeam#191]
Hi,
I am trying to set-up sunbeam (which seems to tick off a lot of boxes on my wishlist)  to run on the Abel computing cluster (Oslo, Norway). That cluster is using Slurm for managing compute jobs.

The sunbeam command line for running it on a cluster is:

    sunbeam run -- --configfile ~/path/to/config.yml --cluster "bsub -n 12" -j 100 -w 90

But for slurm that works differently, at least when take a I look at the snakemake instructions. For instance:

    snakemake -j 999 --cluster-config cluster.json --cluster "sbatch -A {cluster.account} -p {cluster.partition} -n {cluster.n}  -t {cluster.time}"

Just to see if I was understanding I ran a test job on two small datasets. My command was:

    sunbeam run --configfile analysis/test/sunbeam_config.yml --cluster "sbatch --account=nn9305k --mem-per-cpu=3800M --cpus-per-task=4 --time=2:0:0" -j 10 -w 90 

This command worked for using the normal nodes on our cluster and a kraken database set for 56Gb.

But, I am not understanding how I can use the different nodes available on the Abel cluster. There are **normal** nodes (memory 64Gb, 16cpus) and **hugemem** nodes (memory 1Tb, 32 cpus), and for some jobs, e.g. using the full Kraken database, I need the later nodes. How would I set that up with sunbeam? 

With our cluster I can specify to use the hugemem nodes, by adding to the sbatch command: 

    --partition=hugemem

It would not be efficient to start the job with only asking for the hugemem nodes. Those are few and waiting time can be long. So how would I go about to do this with sunbeam? Can I add that to the yml file or not? How would I do that?

Any suggestions are welcome.

**Comment by eclarke** [comment]
I think your easiest option here would be to run the prerequisite jobs on the normal nodes and then switch to the hugemem nodes only for the classification step, something like this:
```bash
# Notice the 'all_decontam' rule specification at the end
 sunbeam run --configfile analysis/test/sunbeam_config.yml \
  --cluster "sbatch --account=nn9305k --mem-per-cpu=3800M \
  --cpus-per-task=4 --time=2:0:0" -j 10 -w 90 all_decontam 
# Once that's done, we just running the Kraken classification (as the preceding steps were already executed)
 sunbeam run --configfile analysis/test/sunbeam_config.yml \
  --cluster "sbatch --account=nn9305k --mem-per-cpu=3800M 
  --cpus-per-task=4 --time=2:0:0 --partition=hugemem" -j 10 -w 90 all_classify 
```

**Comment by louiejtaylor** [comment]
Hi! Thanks for the feedback! I personally have not used rule-specific modifications with this, but I know that it is possible. In the snakemake example you provide, passing that `--cluster-config cluster.json` arg, and then providing a json file that looks something like this:

    {
        "__default__" :
        {
            "account" : "nn9305k",
            "partition" : "normal",
            "memcpu" : "3800M",
            "time" : "2:0:0"
        },
        "kraken_classify":
        {
            "account" : "nn9305k",
            "partition" : "hugemem",
            "mem-per-cpu" : "500G",
            "time" : "2:0:0"
        }
    }

I've adapted this from a qsub config (and I've never used slurm) so I don't know if this syntax is correct, but something like this should do the trick.  Then you can just run sunbeam like:

    sunbeam run --configfile sunbeam_config.yml --cluster-config cluster_config.json --jobs 999 --cluster  "sbatch --account={cluster.account} --partition={cluster.partition} --mem-per-cpu={cluster.memcpu} --cpus-per-task={threads} --time={cluster.time}" -w 30 --keep-going

Pinging @zhaoc1 to check me for accuracy since I know CHOP uses rule-specific config.

**Comment by eclarke** [comment]
I like @louiejtaylor's solution better. I'd suggest going with that one.

**Comment by Thomieh73** [comment]
Hi, thanks for the suggestions. I will try that out and I like @louiejtaylor  suggestion also better. I will let you know if and how I got it to work.

**Comment by Thomieh73** [comment]
Hi, It worked pretty well to run sunbeam with the slurm options using the cluster.json input file.
So what did do exactly:

1. created a cluster.json file with the following lines:

```
    {
	"__default__" :
	{
		"account" : "nn9305k",
		"partition" : "normal",
		"memcpu" : "3800M",
		"time" : "2:0:0",
		"name" : "sb_default"
	},
	"kraken_classify":
	{
		"account" : "nn9305k",
		"partition" : "hugemem",
		"memcpu" : "30000M",
		"time" : "2:0:0",
		"name" : "kraken"
	}
}
```
I added the name option, so that I could monitor the different jobs more easily.

2. And then I ran the sunbeam with the following command:

```
sunbeam run --configfile ~/path/to/sunbeam_config.yml \
	--cluster-config ~/path/to/cluster.json \
	--cluster "sbatch --account={cluster.account} --partition={cluster.partition} --mem-per-cpu={cluster.memcpu} --cpus-per-task={threads} --time={cluster.time} --job-name={cluster.name}"  \
	-j 20 -w 90 
```
That worked without a glitch. This makes it now possible to optimise the cluster usage, by adding more rules to the cluster.json file. For instance the assembly steps are quite memory intensive, and time consuming...

My suggestion would be that you add this example to the manual, since there is bound to be more people working on a slurm driven cluster.
