### ISSUE TITLE
all_decontam is only running all_qc

### ISSUE THREAD

**Issue by scottdaniel** [sunbeam-labs/sunbeam#193]
Hi,

I'm running sunbeam v2.0.0 on a Univa SGE cluster. It seems that executing the sunbeam command with the `all_decontam` is actually only doing up to `all_qc` part. When I look in the output directory, I only see 
```
> (sunbeam) [danielsg@l-0-01 ]$ ls $DATA_DIR/sunbeam_output/qc
01_cutadapt  02_trimmomatic  log
```
Config files are attached as well as the script to launch sunbeam.
[sunbeam.sh.txt](https://github.com/sunbeam-labs/sunbeam/files/2890110/sunbeam.sh.txt)
[stein_sunbeam_config.yml.txt](https://github.com/sunbeam-labs/sunbeam/files/2890114/stein_sunbeam_config.yml.txt)
[cluster.json.txt](https://github.com/sunbeam-labs/sunbeam/files/2890117/cluster.json.txt)
[Snakefile.copy.txt](https://github.com/sunbeam-labs/sunbeam/files/2890122/Snakefile.copy.txt)

I'm going to see if the `all_mapping` will include the qc as well as the decontamination part (and maybe it will stop at decontamination?)

**Comment by eclarke** [comment]
Before I get further into this, I see in your `sunbeam.sh.txt` file that you're executing: 
```
sunbeam run --configfile ./stein_sunbeam_config.yml all_decontam \
    -j 50 -w90 --keep-going --cluster-config \
    ./cluster.json --notemp -p \
 -c "qsub -cwd -r n -v SUNBEAM_DIR -V -o {cluster.output} -e {cluster.error} -l h_vmem={cluster.h_vmem} -l mem_free={cluster.mem_free} -pe smp {threads}" &> log.out
```

The way the `sunbeam run` command works is that you need to add a `--` after `sunbeam run --configfile [file]` as the remaining arguments basically get passed directly to Snakemake. Is that a typo in your file or does that command actually work for you (i.e. it actually launches jobs on a cluster, etc?)

**Comment by eclarke** [comment]
Also, could you attach the log file as well?

**Comment by scottdaniel** [comment]
Hi,

Yep, it actually launches the jobs for me. I had removed the double dashes
in pursuit of another issue but can't remember why.

**Comment by scottdaniel** [comment]
Which one(s)? The ones in .snakemake/logs?

**Comment by eclarke** [comment]
It looks like your sunbeam command is redirecting to a log file. That'd be the one I'd like to see.

**Comment by louiejtaylor** [comment]
Scott, I think the ones in `sunbeam_output/logs/cluster` (if I remember correctly from our convo the other day) will be the useful ones. Probably a trimmomatic log, since it looks like that's what failed

**Comment by scottdaniel** [comment]
Sure, here's a trio of them for one sample...
[trimmomatic_paired.sample=s1.d0.OralSwab.CDED.txt](https://github.com/sunbeam-labs/sunbeam/files/2890743/trimmomatic_paired.sample.s1.d0.OralSwab.CDED.txt)
[find_low_complexity.sample=s1.d0.OralSwab.CDED.txt](https://github.com/sunbeam-labs/sunbeam/files/2890744/find_low_complexity.sample.s1.d0.OralSwab.CDED.txt)
[adapter_removal_paired.sample=s1.d0.OralSwab.CDED.txt](https://github.com/sunbeam-labs/sunbeam/files/2890745/adapter_removal_paired.sample.s1.d0.OralSwab.CDED.txt)

**Comment by scottdaniel** [comment]
Hrmm... running this with `all_mapping` I'm getting failure at the komplexity step:
```
rule remove_low_complexity:
    input: /scr1/users/danielsg/data_files/sunbeam_output/qc/02_trimmomatic/s12.d52.Feces.CDED_1.fastq.gz, /scr1/users/danielsg/data_files/sunbeam_output/qc/log/komplexity/s12.d52.Feces.CDED.filtered_ids
    output: /scr1/users/danielsg/data_files/sunbeam_output/qc/03_komplexity/s12.d52.Feces.CDED_1.fastq.gz
    jobid: 2163
    wildcards: sample=s12.d52.Feces.CDED, rp=1


        gzip -dc /scr1/users/danielsg/data_files/sunbeam_output/qc/02_trimmomatic/s12.d52.Feces.CDED_1.fastq.gz | rbt fastq-filter /scr1/users/danielsg/data_files/sunbeam_output/qc/log/komplexity/s12.d52.Feces.CDED.filtered_ids |        gzip > /scr1/users/danielsg/data_files/sunbeam_output/qc/03_komplexity/s12.d52.Feces.CDED_1.fastq.gz
        
Unable to run job: ERROR! two files are specified for the same host.
Exiting.
Error submitting jobscript (exit code 1):

Job failed, going on with independent jobs.
```

**Comment by eclarke** [comment]
This appears to be an issue with the cluster/job submission process.

Can you attach the file called "log.out" that your command redirects all sunbeam stderr/stdout to in this command: 
```
sunbeam run --configfile ./stein_sunbeam_config.yml all_decontam \
    -j 50 -w90 --keep-going --cluster-config \
    ./cluster.json --notemp -p \
 -c "qsub -cwd -r n -v SUNBEAM_DIR -V -o {cluster.output} -e {cluster.error} -l h_vmem={cluster.h_vmem} -l mem_free={cluster.mem_free} -pe smp {threads}" &> log.out
```

**Comment by scottdaniel** [comment]
> This appears to be an issue with the cluster/job submission process.
> 
> Can you attach the file called "log.out" that your command redirects all sunbeam stderr/stdout to in this command:
> 
> ```
> sunbeam run --configfile ./stein_sunbeam_config.yml all_decontam \
>     -j 50 -w90 --keep-going --cluster-config \
>     ./cluster.json --notemp -p \
>  -c "qsub -cwd -r n -v SUNBEAM_DIR -V -o {cluster.output} -e {cluster.error} -l h_vmem={cluster.h_vmem} -l mem_free={cluster.mem_free} -pe smp {threads}" &> log.out
> ```

Sure, here ya go:
[log.out.txt](https://github.com/sunbeam-labs/sunbeam/files/2898443/log.out.txt)

**Comment by louiejtaylor** [comment]
Scott, do changing your cluster config using either of the suggestions in this thread help?

https://bitbucket.org/snakemake/snakemake/issues/615/error-two-files-are-specified-for-the-same

IIRC komplexity is one of the rules where this would apply

**Comment by scottdaniel** [comment]
> Scott, does changing your cluster config using either of the suggestions in this thread help?
> 
> https://bitbucket.org/snakemake/snakemake/issues/615/error-two-files-are-specified-for-the-same
> 
> IIRC komplexity is one of the rules where this would apply (commas in filenames). Basically changing replacing what's in your current cluster config:
> 
> ```
>     "output" : "logs/cluster/{rule}.{wildcards}.out",
>     "error" : "logs/cluster/{rule}.{wildcards}.err"
> ```
> with this:
> 
> ```
>     "output" : "\"logs/cluster/{rule}.{wildcards}.out\"",
>     "error" : "\"logs/cluster/{rule}.{wildcards}.err\""
> ```

Alright, I'll give this a go... This reminds me of the errors I sometimes get with R and regex, I always forget which parts have to be double-escaped (like for some reason you have to escape the escape!)
