### ISSUE TITLE
RAM and disk space requirements for downloading and installing required databases 

### ISSUE THREAD

**Issue by SamLambrechtsUGent** [sunbeam-labs/sunbeam#195]
I was wondering how many disk space and memory I should reserve when installing sunbeam and downloading or indexing the required databases? 

I'm asking this to prevent trying to build a database that needs >450GB of space and >250GB of RAM (which I don't have access to at the moment)

Might be useful information since you mention there are no pre-existing dependencies or admin privileges needed to install sunbeam, and that it can be deployed on most Linux workstations and clusters

**Comment by eclarke** [comment]
The databases aren't required, in that you don't have to run that part of the workflow if you don't want to (e.g. for assembly or qc). 

For the annotation step using Kraken, the Kraken database size is dependent on your use case and how many genomes you want to include, but most traditionally occupy less than 10Gb. I'd look at the documentation for Kraken here: https://ccb.jhu.edu/software/kraken/. 

Info on the size and availability NCBI databases can be found in the relevant section of the NCBI docs: https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Web&PAGE_TYPE=BlastDocs&DOC_TYPE=Download

Neither of these databases exceed the limits you've mentioned unless you attempt to build a Kraken db on all refseq genomic sequences, for instance.
