### ISSUE TITLE
Use "conda deactivate" instead of "source deactivate"

### ISSUE THREAD

**Issue by eclarke** [sunbeam-labs/sunbeam#198]
New versions of conda warn that "source activate" is deprecated, so at some point we should migrate over (and check the conda version in the install script to make sure it's new enough- this may also be a good thing to check to help resolve the various libcrypto errors)

**Comment by louiejtaylor** [comment]
Doing this after #204/#215 and #213 have been pulled in by the tireless @ressy

**Comment by louiejtaylor** [comment]
Just to clarify @ressy--I should do this in dev? This is not a stable hotfix, correct?

**Comment by ressy** [comment]
Yep I think that makes sense!

**Comment by louiejtaylor** [comment]
Note to self (or other interested parties): I need to check and make sure this is the case, and if not, update these instructions.

```
# Check if on pre-existing path
if [[ $__old_path != *"${__conda_path}/bin"* ]]; then
    warning "** Conda was not detected on your PATH. **"
    warning "This is normal if you haven't installed Conda before."
    warning "To add it to your path, run "
    warning "   'echo \"export PATH=\$PATH:${__conda_path}/bin\" >> ~/.bashrc'"
    warning "and close and re-open your terminal session to apply."
    warning "When finished, run 'source activate ${__sunbeam_env}' to begin."
else
    info "Done. Run 'source activate ${__sunbeam_env}' to begin."
fi
```
