### ISSUE TITLE
sbx_report question

### ISSUE THREAD

**Issue by bcpd** [sunbeam-labs/sunbeam#212]
Hi all -- I have a simple question: why does the sbx_report extension re-run the classification step if the report.rules file only asks for the summary tsv tables? Is there a way to override this behaviour?

Many thanks,
Pedro.

**Comment by louiejtaylor** [comment]
Hi Pedro, thanks for the issue. sbx_report shouldn't re-run the classification steps (assuming your summary tsv exists and is in the correct location). The only reason I can think of is that one of the upstream files has changed or has an updated timestamp--snakemake will rerun rules in this case (and this is the only time I've ever seen something like this happen).

A potential fix: if you rerun the same command, but include the `--touch` parameter (see [snakemake docs](https://snakemake.readthedocs.io/en/stable/executable.html#EXECUTION) for more info), does that fix the problem? The `--touch` flag basically dry-runs the pipeline but updates the timestamps for all the files.

Let me know if any of this doesn't make sense and I can elaborate/debug further. Thanks!

**Comment by bcpd** [comment]
Many thanks for your prompt reply (and apologies for my late reply). The --touch flag appears to have worked.

Thanks!

**Comment by louiejtaylor** [comment]
No worries! Glad that worked!
