### ISSUE TITLE
Assembly rules fail with MEGAHIT 1.2.6

### ISSUE THREAD

**Issue by ressy** [sunbeam-labs/sunbeam#213]
The latest stable release of MEGAHIT, 1.2.6, has a behavior change for the --continue flag when there isn't a previous output directory.  Previously (1.1.3) it would complain about a missing opts.txt and then carry on, but now it complains of a missing options.json and stops with exit code 1, so our assembly rules fail.  I [re-ran the dev build without cache](https://circleci.com/gh/sunbeam-labs/sunbeam/171) to demonstrate.

1.1.3:
```
$ megahit -1 dummyecoli_1.fastq.gz -2 dummyecoli_2.fastq.gz -o dummyecoli_asm --continue
Cannot find dummyecoli_asm/opts.txt
Please check whether the output directory is correctly set by "-o"
Now switching to normal mode.
188.781Gb memory in total.
Using: 169.903Gb.
MEGAHIT v1.1.3
--- [Mon Jul 22 16:04:29 2019] Start assembly. Number of CPU threads 48 ---
...
```

1.2.6:
```
$ megahit -1 dummyecoli_1.fastq.gz -2 dummyecoli_2.fastq.gz -o dummyecoli_asm --continue
megahit: Cannot find /home/jesse/dev/sunbeam-megahit/dummyecoli_asm/options.json, Please check whether the output directory is correctly set by -o
```

We could work around this but from the changelog it looks like the jump from 1.1 to 1.2 is a pretty big one, so we might want to pin the version until we can check the behavior more closely.  Any thoughts?

**Comment by louiejtaylor** [comment]
Pinning sounds good to me for now!

**Comment by louiejtaylor** [comment]
Wait...looking at this, the commit (b4a47fb) failed with this message (looks like the tests succeeded otherwise):

    DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'.

Is this the issue #204 fixes? 😂 such a ridiculous circle

**Comment by ressy** [comment]
I'm not sure why the continue flag is there in our case.  @zhaoc1 do you remember that one?  The rule output is a file while megahit takes a directory, so it is possible the directory could already exist when the rule is called.

From my local testing I think this is what's going on:

 * The DeprecationWarning doesn't cause a nonzero exit code, so if all else is OK, the tests actually pass.  It just happens to be the last and sometimes only notable thing in stdout/stderr so it looks like the cause.
 * In stable, the assembly rule makes an empty output file if *anything* goes wrong, and then at the very end of test_all there's [a check using awk](https://github.com/sunbeam-labs/sunbeam/blob/stable/tests/test_suite.bash#L6) that fails.  But there's no output shown in that case so you don't see the failure occur (we should probably change that).  In dev, the megahit error handling is improved so it actually fails during assembly itself.  But I branched off of stable to try to make a hotfix for this issue.
 * The [log for this build here](https://circleci.com/gh/sunbeam-labs/sunbeam/174) actually looks like megahit 2 is installed (it's buried high up in the messages since the rule supposedly works but makes no contigs) so I need to check what went wrong with my requirements.yml.

So yeah we are in a bit of a ridiculous circle.  I need to see what went wrong with the megahit versioning, we should probably improve on error messages in test_all, and then there's also the conda version issue you just found for #208, the Snakemake version issue we've been trying to solve in #204, and whatever just came up for h5py in #214.  The only unifying feature in all this is multiple external package updates breaking things, I think.

I'm starting to think in the next release we should pin everything at a specific set of versions and only update in deliberate batches.  But for right now I think we're just about to squash a bunch of these bugs at once if we can test and verify a consistent set of packages.

**Comment by louiejtaylor** [comment]
FWIW, testing a fresh local install with `megahit<1.2` in my environment.yml worked fine! I think maybe the issue with that particular commit was that the enviroment.yml says `megahit<2` instead.

**Comment by ressy** [comment]
Aha!  You're right, this is on me.  We need < 1.2, not <2.  Mystery solved.  Well, I'll push another update and make sure ;)

**Comment by ressy** [comment]
That did it.  Thanks Louis.

I'm thinking maybe for these version-related issues we can come up with a consistent package set and then make one hotfix branch that'll go back into stable and dev.  Does that make sense?

**Comment by ressy** [comment]
Ah there we go, a4de7be070eb0fa524384bd7eb9b3b630d1f379d makes it much easier to see:

```
#!/bin/bash -eo pipefail
bash tests/run_tests.bash -e sunbeam
Running setup... ✔
Running build_test_data... ✔
Running test_all... 
Failed command error output:
Check failed on sunbeam_output/annotation/summary/dummyecoli.tsv
x (log: /tmp/tmp.Oi60oD1f9u/test_all.[out/err])
-- TESTS FAILED --
Exited with code 1
```

Also, I take that back about a single hotfix since there's only a couple version-related fixes to do.  I'll get this one wrapped up now.

**Comment by louiejtaylor** [comment]
So. No one should encounter this particular error since @ressy's fix was implemented...but for some reason, I still had megahit 1.2.6 in one of my sunbeam envs. I got the same error Jesse did above, but rather than exiting in error, a bunch of empty contig files chugged merrily along. Is this what happens whenever megahit errors? Should I open a separate issue for this? Or was this just a fluke?

**Comment by ressy** [comment]
In the latest stable version the assembly rules will create an empty file for *any* error condition, which includes dumb stuff like syntax errors.  But in dev we only create an empty file for exit code 255, where it complains of no contigs, so I think it should behave better going forward.  (This was changed in #194.)
