### ISSUE TITLE
h5py not installed by conda

### ISSUE THREAD

**Issue by louiejtaylor** [sunbeam-labs/sunbeam#214]
I'm flummoxed. Installing the latest version of Sunbeam does not install the h5py library. This breaks the kraken-biom step (rule `kraken_biom`). But what I don't understand is...we require kraken-biom in the environment.yml, which [requires](https://bioconda.github.io/recipes/kraken-biom/README.html) the biom-format package (which was installed in my recent fresh install), which [requires](https://bioconda.github.io/recipes/biom-format/README.html#package-biom-format) h5py. What gives?? If you `conda install kraken-biom -c bioconda`, h5py comes along just fine.

If you need this fixed, running `conda install h5py -c bioconda` from within the Sunbeam env patches the problem.

A quick workaround is obviously to drop h5py into our environment.yml. But we shouldn't have to do that.

Also, this is not our fault. I think.

**Comment by ressy** [comment]
I see it too.  Locally with dev using my installer debug tool, and [on CircleCI](https://circleci.com/gh/sunbeam-labs/sunbeam/187).

A couple quick thoughts bouncing off of what we were talking about earlier:

 * kraken-biom is provided by bioconda (requires biom-format)
 * biom-format is provided by both bioconda (requires h5py) and conda-forge (does not require h5py)
 * h5py is provided by conda-forge

So are we inadvertently picking up conda-forge's biom-format now and it doesn't give the implicit dependencies kraken-biom expects (just like with rust-bio-tools back in #200)?

```
$ conda list | egrep 'h5py|biom-format|kraken-biom'
biom-format               2.1.7           py36h3010b51_1002    conda-forge
kraken-biom               1.0.1                      py_2    bioconda
```

In case we need it, we now can specify channels on a per-package basis: https://github.com/conda/conda/issues/5693#issuecomment-505579189.  But in this case we have our channel priorities defined correctly as far as I can see.

**Comment by ressy** [comment]
> Also, this is not our fault. I think.

Yep, I think this one's on bioconda, actually.  If you follow [their instructions for channel setup](https://bioconda.github.io/user/install.html#set-up-channels) starting from scratch and then install kraken-biom, it breaks like you saw.

```
$ conda config --add channels defaults
Warning: 'defaults' already in 'channels' list, moving to the top
$ conda config --add channels bioconda
$ conda config --add channels conda-forge
$ conda create --name kraken-biom-test kraken-biom
$ kraken-biom --max D -o taxa.biom dummyecoli-taxa.tsv
Library 'h5py' not found, unable to write BIOM 2.x (HDF5) files.
Defaulting to BIOM 1.0 (JSON).
Traceback (most recent call last):
  File "/home/jesse/dev/sunbeam-issue-214/anaconda3/bin/kraken-biom", line 10, in <module>
    sys.exit(main())
  File "/home/jesse/dev/sunbeam-issue-214/anaconda3/lib/python3.7/site-packages/kraken_biom.py", line 379, in main
    out_fp = write_biom(biomT, args.output_fp, args.fmt, args.gzip)
  File "/home/jesse/dev/sunbeam-issue-214/anaconda3/lib/python3.7/site-packages/kraken_biom.py", line 226, in write_biom
    biomT.to_json(biomT.generated_by, direct_io=biom_f)
  File "/home/jesse/dev/sunbeam-issue-214/anaconda3/lib/python3.7/site-packages/biom/table.py", line 4497, in to_json
    raise TableException("Unsupported matrix data type.")
biom.exception.TableException: Unsupported matrix data type.
```

They specifically say "It is important to add them in this order so that the priority is set correctly (that is, conda-forge is highest priority)" so this whole implicit dependency thing seems like an oversight.  Maybe h5py should be listed in their own metadata for kraken-biom, if they really do intend for the conda-forge package to get installed.

**Comment by louiejtaylor** [comment]
Ooh, thank you for figuring this out. I really like that double-colon syntax for specifying channel. We actually don't include `biom-format` in our environment.yml, so I don't think that the double-colon syntax would work (although it is quite nifty!). 

Reordering the channels to the (wrong?) order they're in currently in the stable branch would likely fix this issue (unless there are other differences) since it would pull the biopython version instead [I think] which has the dependencies hooked up properly. But, IIRC, we changed the channel order for a reason and it is correct now in dev.

Based on this, I think I vote for the lazy solution of putting h5py in our environment.yml, and then poking the person who does the conda-forge metadata (if we can find them) so that there's a permanent, reasonable fix. What do you think?

**Comment by ressy** [comment]
Ah you're right, we would need to both include biom-format explicitly and give the channel with the double-colon.  Just adding h5py directly does sound like the simplest way to go for now so I'd also opt for that.  And then I think it'll be the bioconda maintainers we'll alert (since it's their kraken-biom that's making assumptions about its indirect dependencies).

**Comment by louiejtaylor** [comment]
Awesome, thanks. I can take care of this!
