### ISSUE TITLE
Assembly rules with megahit.

### ISSUE THREAD

**Issue by Thomieh73** [sunbeam-labs/sunbeam#226]
Hey guys,

I am running sunbeam on my latest metagenome data after doing a fresh install from scratch to get the latest version of sunbeam.

Now I am trouble shooting why the assembly with megahit constantly fails. When I check the megahit jobs  on or clustersI see that it only has one cpu, while I specified 16.

So I started digging in the code.

I have downloaded the latest version of sunbeam-stable today, using the command: `git clone -b stable https://github.com/eclarke/sunbeam sunbeam-stable` and the assembly.rules file shows this (only showing the top line):

```
# -*- mode: Snakemake -*-
#
# Contig building and other assembly rules
#
# Requires Megahit.

rule all_assembly:
    """Build contigs for all samples."""
    input:
        TARGET_ASSEMBLY

ruleorder: megahit_paired > megahit_unpaired
          
rule megahit_paired:
    input:
        r1 = str(QC_FP/'decontam'/'{sample}_1.fastq.gz'),
        r2 = str(QC_FP/'decontam'/'{sample}_2.fastq.gz')
    output:
        str(ASSEMBLY_FP/'megahit'/'{sample}_asm'/'final.contigs.fa')
    params:
        out_fp = str(ASSEMBLY_FP/'megahit'/'{sample}_asm')
    shell:
        """
        ## turn off bash strict mode
        set +o pipefail

        ## sometimes the error is due to lack of memory
        exitcode=0
        megahit -1 {input.r1} -2 {input.r2} -o {params.out_fp} --continue || exitcode=$?
        
        if [ $exitcode -eq 255 ]
        then
            echo "Empty contigs"
        elif [ $exitcode -gt 1 ]
        then
            echo "Check your memory"
        fi
        if [ ! -a {output} ]; then touch {output}; fi
```

But when I check the same file in your github repo I find this:

```
# -*- mode: Snakemake -*-
#
# Contig building and other assembly rules
#
# Requires Megahit.

rule all_assembly:
    """Build contigs for all samples."""
    input:
        TARGET_ASSEMBLY

ruleorder: megahit_paired > megahit_unpaired

rule megahit_paired:
    input:
        r1 = str(QC_FP/'decontam'/'{sample}_1.fastq.gz'),
        r2 = str(QC_FP/'decontam'/'{sample}_2.fastq.gz')
    output:
        str(ASSEMBLY_FP/'megahit'/'{sample}_asm'/'final.contigs.fa')
    params:
        out_fp = str(ASSEMBLY_FP/'megahit'/'{sample}_asm')
    threads:
        Cfg['assembly']['threads']
    shell:
        """
        ## turn off bash strict mode
        set +o pipefail

        ## sometimes the error is due to lack of memory
        exitcode=0
        megahit -t {threads} -1 {input.r1} -2 {input.r2} -o {params.out_fp} --continue || exitcode=$?

        if [ $exitcode -eq 255 ]
        then
            echo "Empty contigs"
            touch {output}
        elif [ $exitcode -gt 1 ]
        then
            echo "Check your memory"
        fi
        """
```

The difference is that in the later version it does indicate the threads. 

I was thinking that if I replace my original with the file on your repository, than it should work again after doing a new run with bash.install. is that right?

**Comment by louiejtaylor** [comment]
I think you're right--we have made a few changes to MEGAHIT rules (including adding the threads requirement [in Jan](https://github.com/sunbeam-labs/sunbeam/issues/188)). Either replacing the rules file from the corresponding branch (e.g. stable) or just cd-ing into the repo and running `git pull` before redoing the Sunbeam install should solve things, I think.

I remember there being another [MEGAHIT-related issue](https://github.com/sunbeam-labs/sunbeam/issues/213), specifically relating to which version of MEGAHIT was installed--if you run into errors using MEGAHIT, you might check to make sure your `environment.yml` file (in the base sunbeam directory) matches the current stable one, and then reinstalling Sunbeam.

Let us know if this works or if you have any trouble!

**Comment by Thomieh73** [comment]
Okay i did the following:
- replaced the rules file in the directory: /sunbeam-stable/assembly.
- next I ran git pull, which indicated everything was up to date.
- removed my current sunbeam environment
- ran install.sh to build a new sunbeam environment.

and then I ran a sunbeam job with the assembly option and 16 threads.
That worked. 

So I close this issue.
