### ISSUE TITLE
Getting an error: No module named 'semantic_version'

### ISSUE THREAD

**Issue by junglee0713** [sunbeam-labs/sunbeam#227]
Hi all, 

I recently installed sunbeam v 2.0.2 and was getting an error like 

ModuleNotFoundError in line 19 of /home/leej39/sunbeam-stable/Snakefile:
No module named 'semantic_version'
  File "/home/leej39/sunbeam-stable/Snakefile", line 19, in <module>
  File "/home/leej39/sunbeam-stable/sunbeamlib/__init__.py", line 12, in <module>

The command I used was 

sunbeam run --configfile=/scr1/users/leej39/Elgarten/sunbeam_config.yml

I was wondering if anyone had a similar issue and knew how to fix it. Thanks!

Jung-Jin

**Comment by louiejtaylor** [comment]
This is odd. Did you have any issues with the sunbeam install? I think that package should come in on install (or at least it does for me).

**Comment by junglee0713** [comment]
Hi Louis,

I just reinstalled the sunbeam and noticed that the test fails -- the following is what I see

(sunbeam) [leej39@l-0-01 sunbeam-stable]$ tests/run_tests.bash -e sunbeam
Running setup... ✔
Running build_test_data... 
Failed command error output:
Traceback (most recent call last):
  File "/home/leej39/miniconda3/envs/qiime2-2019.7/bin/sunbeam", line 6, in <module>
    from sunbeamlib.scripts.command import main
  File "/home/leej39/miniconda3/envs/qiime2-2019.7/lib/python3.6/site-packages/sunbeamlib/__init__.py", line 12, in <module>
    from semantic_version import Version
ModuleNotFoundError: No module named 'semantic_version'
x (log: /scr1/users/leej39/tmp/tmp.v52EbMqmKo/build_test_data.[out/err])
-- TESTS FAILED --
DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'.

It looks like sunbeam is somehow installed under another environment (qiime2-2019.7) which is odd.

**Comment by louiejtaylor** [comment]
I see that...it looks like for some reason there is an executable called `sunbeam` in the bin directory of one of your other (`/home/leej39/miniconda3/envs/qiime2-2019.7/`) conda envs. I can't for the life of me think of why conda would look there, rather than in the path for the sunbeam environment (which you clearly have activated). To me, this looks like something is wonky with your $PATH variable, although I have limited experience with this sort of thing and may pull Jesse in if we can't figure this out.

Troubleshooting:

 1. Could you paste the output of `echo $PATH`, both with no environment activated (i.e. in a fresh session), and after running `conda activate sunbeam` (in the env you've freshly installed). Also, if you still have that session open where you were getting that error, you can also run `echo $PATH` there and see if there's anything to tell us why the heck your shell is looking in `/home/leej39/miniconda3/envs/qiime2-2019.7/` rather than `/home/leej39/miniconda3/envs/sunbeam/` when you are clearly working within the sunbeam env.
 2. Do you modify $PATH in any way on startup, e.g. in your .bashrc file? If so, do you mind pasting the relevant lines?
 3. What version of conda are you running? (`conda --version`)

If you're coming to Journal Club tomorrow I can also work with you after to debug this and it'll likely go quicker!

**Comment by junglee0713** [comment]
Thank you so much for your time Louis. I will be coming to Journal Club tomorrow.

1. 
echo $PATH under sunbeam env: (the session was still open)
(sunbeam) [leej39@l-0-01 sunbeam-stable]$ echo $PATH
/home/leej39/miniconda3/envs/sunbeam/bin:/home/leej39/miniconda3/envs/qiime2-2019.7/bin:/home/leej39/miniconda3/envs/sunbeam/bin:/home/leej39/miniconda3/condabin:/cm/shared/apps_chop/R/3.6.0/lib64/R/bin:/cm/shared/apps_chop/gsl/2.5/bin:/cm/shared/apps_chop/gdal/2.4.0/bin:/cm/shared/apps_chop/hdf5/1.10.4/bin:/cm/shared/apps_chop/jdk/1.8.0_144/bin:/scr1/users/leej39/Jason_Xu_BOTA/BOTA:/home/leej39/biobakery-metaphlan2-0c3ed7b7718b:/home/leej39/biobakery-metaphlan2-0c3ed7b7718b/utils:/cm/shared/apps/uge/8.6.6/bin/lx-amd64:/cm/shared/easybuild/software/EasyBuild/3.8.1/bin:/cm/local/apps/environment-modules/4.2.1/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/sbin:/cm/local/apps/environment-modules/4.2.1/bin:/opt/dell/srvadmin/bin:/home/leej39/miniconda3/bin:/home/leej39/dnabc-master:/home/leej39/seqtk:/home/leej39/vsearch-2.8.2-linux-x86_64/bin:/home/leej39/miniconda3/envs/panphlan/bin:/home/leej39/miniconda3/envs/panphlan/bin:/home/leej39/tree-1.8.0:/home/leej39/bin:/home/leej39/pigz-2.4

echo $PATH uner (base):
(base) [leej39@l-0-01 sunbeam-stable]$ echo $PATH
/home/leej39/miniconda3/bin:/home/leej39/miniconda3/envs/qiime2-2019.7/bin:/home/leej39/miniconda3/envs/sunbeam/bin:/home/leej39/miniconda3/condabin:/cm/shared/apps_chop/R/3.6.0/lib64/R/bin:/cm/shared/apps_chop/gsl/2.5/bin:/cm/shared/apps_chop/gdal/2.4.0/bin:/cm/shared/apps_chop/hdf5/1.10.4/bin:/cm/shared/apps_chop/jdk/1.8.0_144/bin:/scr1/users/leej39/Jason_Xu_BOTA/BOTA:/home/leej39/biobakery-metaphlan2-0c3ed7b7718b:/home/leej39/biobakery-metaphlan2-0c3ed7b7718b/utils:/cm/shared/apps/uge/8.6.6/bin/lx-amd64:/cm/shared/easybuild/software/EasyBuild/3.8.1/bin:/cm/local/apps/environment-modules/4.2.1/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/sbin:/cm/local/apps/environment-modules/4.2.1/bin:/opt/dell/srvadmin/bin:/home/leej39/miniconda3/bin:/home/leej39/dnabc-master:/home/leej39/seqtk:/home/leej39/vsearch-2.8.2-linux-x86_64/bin:/home/leej39/miniconda3/envs/panphlan/bin:/home/leej39/miniconda3/envs/panphlan/bin:/home/leej39/tree-1.8.0:/home/leej39/bin:/home/leej39/pigz-2.4

2. 
**maybe this is relevant** -- the last two lines of .bashrc goes like
export PATH=/home/leej39/miniconda3/envs/sunbeam/bin/:$PATH
export PATH=/home/leej39/miniconda3/envs/qiime2-2019.7/bin/:$PATH

3. 
I am using conda 4.7.11
(base) [leej39@l-0-01 ~]$ conda --version
conda 4.7.11

4. 
To install sunbeam, I followed the instruction:
git clone -b stable https://github.com/sunbeam-labs/sunbeam sunbeam-stable
cd sunbeam-stable
./install.sh
tests/run_tests.bash -e sunbeam

**Comment by louiejtaylor** [comment]
Hmm, your .bashrc does look relevant. A few things to try:

 1. Comment out the last line of your .bashrc, then open a new shell session, run `source activate sunbeam`, `cd` to the sunbeam-stable directory, and then run the tests (`tests/run_tests.bash -e sunbeam`). Also, try running the tests without specifying an env (`tests/run_tests.bash`) and see if that also fails.
 2. Based on your first echo of $PATH, it looks like it should have looked in /home/leej39/miniconda3/envs/sunbeam/bin/ first for the sunbeam executable, which is the correct behavior. Could you run `ls /home/leej39/miniconda3/envs/sunbeam/bin/` and paste the output here? (If there's too much, `ls /home/leej39/miniconda3/envs/sunbeam/bin/s*` should suffice).

**Comment by junglee0713** [comment]
1. I commented out the last line of .bashrc, opened a new terminal, activated sunbeam environment and ran the command tests/run_tests.bash -e sunbeam, but it still fails, with the following error message:

(sunbeam) [leej39@l-0-01 sunbeam-stable]$ tests/run_tests.bash -e sunbeam
Running setup... ✔
Running build_test_data... 
Failed command error output:
tests/run_tests.bash: line 194: sunbeam: command not found
x (log: /scr1/users/leej39/tmp/tmp.H9As9a2VWG/build_test_data.[out/err])
-- TESTS FAILED --
DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'.

Without specification, `tests/run_tests.bash` is stuck at **Running setup...** (more than 20mins now)

2. the output does not contain the sunbeam executable:

(base) [leej39@l-0-01 ~]$ ls /home/leej39/miniconda3/envs/sunbeam/bin/s*
/home/leej39/miniconda3/envs/sunbeam/bin/sam2vcf.pl
/home/leej39/miniconda3/envs/sunbeam/bin/sam-dump
/home/leej39/miniconda3/envs/sunbeam/bin/sam-dump.2
/home/leej39/miniconda3/envs/sunbeam/bin/sam-dump.2.9.6
/home/leej39/miniconda3/envs/sunbeam/bin/samtools
/home/leej39/miniconda3/envs/sunbeam/bin/samtools.pl
/home/leej39/miniconda3/envs/sunbeam/bin/sccmap
/home/leej39/miniconda3/envs/sunbeam/bin/sclient
/home/leej39/miniconda3/envs/sunbeam/bin/seedtop
/home/leej39/miniconda3/envs/sunbeam/bin/segmasker
/home/leej39/miniconda3/envs/sunbeam/bin/seq_cache_populate.pl
/home/leej39/miniconda3/envs/sunbeam/bin/seqdb_demo
/home/leej39/miniconda3/envs/sunbeam/bin/seqdb_perf
/home/leej39/miniconda3/envs/sunbeam/bin/serialver
/home/leej39/miniconda3/envs/sunbeam/bin/sexp-conv
/home/leej39/miniconda3/envs/sunbeam/bin/sfdp
/home/leej39/miniconda3/envs/sunbeam/bin/sff-dump
/home/leej39/miniconda3/envs/sunbeam/bin/sff-dump.2
/home/leej39/miniconda3/envs/sunbeam/bin/sff-dump.2.9.6
/home/leej39/miniconda3/envs/sunbeam/bin/shasum
/home/leej39/miniconda3/envs/sunbeam/bin/sim_client
/home/leej39/miniconda3/envs/sunbeam/bin/snakemake
/home/leej39/miniconda3/envs/sunbeam/bin/snakemake-bash-completion
/home/leej39/miniconda3/envs/sunbeam/bin/soap2sam.pl
/home/leej39/miniconda3/envs/sunbeam/bin/splain
/home/leej39/miniconda3/envs/sunbeam/bin/sqlite3
/home/leej39/miniconda3/envs/sunbeam/bin/sqlite3_analyzer
/home/leej39/miniconda3/envs/sunbeam/bin/srapath
/home/leej39/miniconda3/envs/sunbeam/bin/srapath.2
/home/leej39/miniconda3/envs/sunbeam/bin/srapath.2.9.6
/home/leej39/miniconda3/envs/sunbeam/bin/sra-pileup
/home/leej39/miniconda3/envs/sunbeam/bin/sra-pileup.2
/home/leej39/miniconda3/envs/sunbeam/bin/sra-pileup.2.9.6
/home/leej39/miniconda3/envs/sunbeam/bin/sra-sort
/home/leej39/miniconda3/envs/sunbeam/bin/sra-sort.2
/home/leej39/miniconda3/envs/sunbeam/bin/sra-sort.2.9.6
/home/leej39/miniconda3/envs/sunbeam/bin/sra-stat
/home/leej39/miniconda3/envs/sunbeam/bin/sra-stat.2
/home/leej39/miniconda3/envs/sunbeam/bin/sra-stat.2.9.6
/home/leej39/miniconda3/envs/sunbeam/bin/srptool
/home/leej39/miniconda3/envs/sunbeam/bin/starcode
/home/leej39/miniconda3/envs/sunbeam/bin/sxpm

**Comment by junglee0713** [comment]
`tests/run_tests.bash`, without `-e sunbeam` specification, works!

(sunbeam) [leej39@l-0-01 sunbeam-stable]$ tests/run_tests.bash
Running setup... ✔
Running build_test_data... ✔
Running test_all... ✔
Running test_blank_fp_behavior... ✔
Running test_extensions... ✔
Running test_get_paired_unpaired... ✔
Running test_guess_with_inconsistent_samples... ✔
Running test_guess_with_index_files_present... ✔
Running test_guess_with_two_samples... ✔
Running test_mapping... ✔
Running test_optional_cutadapt... ✔
Running test_pair_concordance... ✔
Running test_single_end... ✔
Running test_sunbeam_get... ✔
Running test_template_option... ✔
Running test_use_conda... ✔
Running test_version_check... ✔
-- TESTS SUCCEEDED --
DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'.

**Comment by louiejtaylor** [comment]
Interesting! Since the tests ran fine not using your env, this looks like your sunbeam conda env is broken for some reason, which should be easy to fix. What I would do is just deactivate the sunbeam environment if you're in it (`conda deactivate`), and then `cd` to the sunbeam-stable dir, then rerun the install for the env only:

    ./install.sh -u env

**Comment by junglee0713** [comment]
Hi Louis,

Finally it seems working! `./install.sh -u env` and `tests/run_tests.bash -e sunbeam` didn't throw any errors (see below) and the actual jobs I wanted to submit seem to be processed well. Thank you for your time and effort so far -- **you saved my day!**

(base) [leej39@l-0-01 sunbeam-stable]$ ./install.sh -u env
2019-09-19 14:40:47 UTC [     info] Starting Sunbeam installation...
2019-09-19 14:40:47 UTC [     info]     Conda path:   /home/leej39/miniconda3
2019-09-19 14:40:47 UTC [     info]     Sunbeam src:  /home/leej39/sunbeam-stable
2019-09-19 14:40:47 UTC [     info]     Sunbeam env:  'sunbeam'
DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'.
2019-09-19 14:40:55 UTC [     info] Conda already installed.
2019-09-19 14:40:55 UTC [     info] Creating Sunbeam environment...
2019-09-19 14:56:25 UTC [     info] Environment installed/updated; (re)installing Sunbeam library...
DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'.
2019-09-19 14:56:46 UTC [     info] Done. Run 'source activate sunbeam' to begin.

(base) [leej39@l-0-01 sunbeam-stable]$ source activate sunbeam
(sunbeam) [leej39@l-0-01 sunbeam-stable]$ tests/run_tests.bash -e sunbeam
Running setup... ✔
Running build_test_data... ✔
Running test_all... ✔
Running test_blank_fp_behavior... ✔
Running test_extensions... ✔
Running test_get_paired_unpaired... ✔
Running test_guess_with_inconsistent_samples... ✔
Running test_guess_with_index_files_present... ✔
Running test_guess_with_two_samples... ✔
Running test_mapping... ✔
Running test_optional_cutadapt... ✔
Running test_pair_concordance... ✔
Running test_single_end... ✔
Running test_sunbeam_get... ✔
Running test_template_option... ✔
Running test_use_conda... ✔
Running test_version_check... ✔
-- TESTS SUCCEEDED --

**Comment by louiejtaylor** [comment]
That's great! Hopefully it was just a one-off problem that never happens again. I'll close this issue but feel free to reopen if you see more weirdness happening when you start running Sunbeam.
