### ISSUE TITLE
blast database

### ISSUE THREAD

**Issue by wangjiawen2013** [sunbeam-labs/sunbeam#231]
Dear,
Two BLAST databases, one nucleotide (‘bacteria’) and one protein (‘card’) are used in sunbeam's document (https://sunbeam.readthedocs.io/en/latest/usage.html#outputs). Could provide the links to these database ? I cannot get these databases, or could you teach us how to make these databases ?

**Comment by ressy** [comment]
Hi Jiawen,

The documentation doesn't go into detail on the steps required to build those hypothetical custom databases, but you can follow NCBI's documentation to create your own from whatever FASTA inputs you like: https://www.ncbi.nlm.nih.gov/books/NBK279688/

You can use the standard databases too, for example a local copy of the typical "nt" database.  See "Databases" at the bottom of this page:
https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Web&PAGE_TYPE=BlastDocs&DOC_TYPE=Download 

If you download all of the tar.gz files for a particular name and extract them in a directory, you'll have a local copy of that database: https://ftp.ncbi.nlm.nih.gov/blast/db/
Or you can try using NCBI's tools to download them:
https://www.ncbi.nlm.nih.gov/books/NBK537770/

(Note that Sunbeam follows BLAST's naming scheme of directory + name of database, so "nt/nt" in the example in the documentation means "inside the directory named nt, use the database files prefixed with nt."  And for the example protein databases, the virulence_factors directory could contain a few different databases, but Sunbeam would use the one whose files start with virdb, based on that configuration.)

Jesse
