### ISSUE TITLE
bracken?

### ISSUE THREAD

**Issue by bcpd** [sunbeam-labs/sunbeam#265]
Hi all,

Are there plans to add bracken functionality, e.g. through an extension?

**Comment by louiejtaylor** [comment]
Hi @bcpd, thank you for the issue. We don't have any plans to add bracken/any steps downstream of kraken2 either in the main pipeline or as an extension at the moment.

If it's something you'd like to run downstream of Sunbeam more than once, you might consider writing an extension--we have an [extension template](https://github.com/sunbeam-labs/sbx_template) and a bunch of extensions on our website you can work off of: https://www.sunbeam-labs.org/. (My favorite example of an extension that's easy to understand is [sbx_kraken_uniq](https://github.com/ArwaAbbas/sbx_kraken_uniq).) 

If you do decide to take a crack at it, I'm happy to answer questions if you have them! No pressure either way--if it's something you'll do for multiple projects an extension will probably make your life easier. If it's just for a one-off analysis I probably wouldn't bother writing an extension.

**Comment by bcpd** [comment]
Thank you, @louiejtaylor . Writing an extension is probably the way to go. Out of curiosity: does the sunbeam team not consider bracken a natural kraken(2) partner, given how well they complement each other?

**Comment by louiejtaylor** [comment]
I can't say that we won't include it in the future, but we don't have any near-term plans to add bracken to the pipeline. We do appreciate the suggestion, and the issue! I'm going to close this for the moment, but feel free to reopen/open a new issue if you do decide to take a whack at a bracken extension and would like feedback,
