### ISSUE TITLE
Environment creation failing on CircleCI

### ISSUE THREAD

**Issue by ressy** [sunbeam-labs/sunbeam#269]
Our latest scheduled tests are failing, I think because the conda environment setup is using too much RAM.  This step slowly climbs up to 4 GB higher than the system started (and the docs say we get 4 GB) and then dies with exit code 137:

    conda env update --name=sunbeam --file environment.yml

On a side note, CircleCI's [SSH support for jobs](https://circleci.com/docs/2.0/ssh-access-jobs/) is wonderfully easy.  I can log in and see the command fail but can't find a good way to work around it.  CircleCI won't let me enable swap as the sorta-root-user in the container.

Maybe the latest changes in the environment file were just the final straw for conda's memory usage, but I also don't see why it should be so demanding for a listing of ~25 packages at the top level.  It sounds like conda just does tend to use a ton of RAM when figuring out packages.

https://github.com/conda/conda/issues/5003

If I instead use the latest explicit list of packages, it moves along smoothly through most of the file, but hits one particular conda-forge package (`gdk-pixbuf-2.36.12-haf2c3b9_1004`) and then fails with 404:

    conda create --name=sunbeam --file stable_env/v3.0.0.txt

So maybe those old builds persist even for even less time than I'd thought?  Weird thing on that particular one is that I see builds ending in 1001, 1002, 1003, and 1005, just not 1004.  I swapped out _1005 and it finished OK.  Not sure that bodes well for the stability of the those URLs though.

**Comment by louiejtaylor** [comment]
Hmm, that's not good. I think there might be an option to exclude the build number from the conda env dump, but a quick google didn't find anything so I may be mis-remembering. I am surprised that the builds are so ethereal though...

On another note. Shouldn't CircleCI not even be setting up an env? We haven't made changes to `environment.yml` recently (that I know of), so shouldn't it just be using a cached miniconda dir? Or am I misunderstanding that aspect as well?

**Comment by ressy** [comment]
Hey wait, you're right, we cache the whole miniconda3 directory using a checksum on the environment file and that's been the same for a while now.  But when it started failing earlier today it claimed there was no cache available even though the key was still identical.  Ah here it is, they're saved for [up to 30 days](https://circleci.com/docs/2.0/caching/#cache-expiration).  That cache (`v3-dependencies-ImvatbS46QnkM8JqMAJqKt4f09bMMPKGfJjZZEpytS4=`) was created on [January 22nd](https://circleci.com/gh/sunbeam-labs/sunbeam/380), so it should expire around... ten days from now.  Huh. 
 Maybe the "up to" factored in for some reason some time in the last week and it got dumped earlier.

So I think we're handling all of that correctly but for one reason or another the conda cache was gone as of today.  The other assumption I'm making is that the RAM usage just happened to be a little lower last time around even with the same package list YAML (a different exact list getting calculated this time maybe?) and it's just now giving us trouble.  But none of that gives me any clarity on what the best fix would be.  Being able to leave off the exact build number would be great, but I haven't seen that option and the URLs don't look like they'd support it directly, at least not on conda-forge.

**Comment by louiejtaylor** [comment]
I've just noticed that the stable weekly build seems to be working fine: https://circleci.com/gh/sunbeam-labs/sunbeam/395--and it did have to recreate the env. So maybe the differences between the envs there is informative?

**Comment by ressy** [comment]
Yeah, I wonder if for whatever reason conda is using just a bit more RAM to resolve dependencies for the packages listed in dev's environment.yml, and that's pushing it over the edge.  I was thinking we could try adding an argument to install.sh to use an explicit file like `stable_env/v3.0.0.txt` and see what happens.
