### ISSUE TITLE
exit code -11; problem with test

### ISSUE THREAD

**Issue by rakeuler** [sunbeam-labs/sunbeam#277]
I just installed Sunbeam on the HPC, and I am encountering a problem with the test. I get the following error message:
Error occurs when assembling contigs for k = 21, please refer to /tmp/tmp.HSpwkQgCiV/sunbeam_output/assembly/megahit/dummyecoli_asm/log for detail
[Exit code -11]
Waiting at most 5 seconds for missing files.
MissingOutputException in line 14 of /zhome/rakeuler/software/sunbeam-stable/rules/assembly/assembly.rules:
Missing files after 5 seconds:
/tmp/tmp.HSpwkQgCiV/sunbeam_output/assembly/megahit/dummyecoli_asm/final.contigs.fa
This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.

**Comment by arturotorreso** [comment]
Hi @rakeuler, 

I had the same issue that you had, so I installed the latest version of Megahit (1.2.9) and ran it separately from the sunbeam pipeline (but the same input files and flags). That worked fine. Sunbeam uses Megahit 1.1.3, so probably some major updates have been added since then.

**Comment by tickteng** [comment]
Same issue.
Installed package for megahit 1.1.3. but still get the same error.

**Comment by ArwaAbbas** [comment]
I also got the same error after installing sunbeam; the test failed at the "megahit_paired" rule. Haven't tried to install the new version of MegaHit though. 
The image below has the details of the rule call and the error output:

![image](https://user-images.githubusercontent.com/17831127/85141938-990c5100-b215-11ea-9656-f8cd7eedae11.png)

**Comment by ArwaAbbas** [comment]
Update to this issue:

If you install the developmental version of Sunbeam directly from GitHub (future version 3.0) rather than the sunbeam-stable, the tests work!

**Comment by Ulthran** [comment]
Haven't seen this issue pop up with sunbeam3 yet and megahit should resolve to a later version in the new assembly env. Marking this as closed for now, please open a new issue if you encounter it with sunbeam3.
