### ISSUE TITLE
How should I name my fastq files??

### ISSUE THREAD

**Issue by bitcometz** [sunbeam-labs/sunbeam#278]
I put CTL1_R1_001.fastq.gz and CTL1_R2_001.fastq.gz under the path "mypath/00.sunbeam" and then run:
sunbeam init my_project --data_fp mypath/00.sunbeam

then report the errors:

Creating project folder at my_project...
Guessing sample name format from files in mypath/00.sunbeam...
Warning: samples have inconsistent numbers of _ or . characters
  Best guess: {sample}{sample}
Error: could not create sample list. Specify correct sample filename format using --format.
  Reason: no samples matching the given format found.

So are the wrong names for my fastq files?
Is there an example show me how to name the input files?

Thanks!

**Comment by razz1618** [comment]
Use "--format" followed by  {sample}_R{rp}_001.fastq.gz, where {sample} defines the sample name and {rp} defines the 1 or 2 in the read pair. for e.g.

sunbeam init --data_fp /path/to/fast_files/directory /path/to/project/directory **--format {sample}_R{rp}.fastq.gz**

**Comment by louiejtaylor** [comment]
Thanks, @razz1618! @bitcometz, please feel free to reopen this if you need clarification. The goal is to not require you to name samples a specific way, but rather to let Sunbeam deal with however your samples are named using the `--format` option. This [section of the documentation](https://sunbeam.readthedocs.io/en/latest/usage.html#creating-a-new-project-using-local-data) may be helpful.
