### ISSUE TITLE
Adapter error- Error in rule adapter_removal_paired:

### ISSUE THREAD

**Issue by razz1618** [sunbeam-labs/sunbeam#281]
Hi, i have paired samples with adapters removed. i used **“”** to skip adapter removal as per the sunbeam documentation. But I get the following error while running QC and decontam-
**cutadapt: error: Character '“' in adapter sequence '“”' is not a valid IUPAC code. Use only characters XACGTURYSWKMBDHVN.**

I guess cutadapt rule isn't accepting **“”** ( I do not have the used adapter sequence)

For full log-
[log.txt](https://github.com/sunbeam-labs/sunbeam/files/5280498/log.txt)

**Comment by louiejtaylor** [comment]
Hi razz1618, very sorry for the slow response. I think there's a slight character difference here

The character you want to use to skip adapter removal is `""` (U+0022 : QUOTATION MARK).

Our documentation turned this string into `““` (U+201C : LEFT DOUBLE QUOTATION MARK).

This is our bad--I think the documentation software swaps around some of the unicode characters for "style", but these stylish quotation marks are gibberish to the software.

I'll leave this issue open until we add backticks around the relevant documentation quotation marks.

**Comment by razz1618** [comment]
Thanks. I kept the default adapter sequence in the config file and the process was completed without any error.
