### ISSUE TITLE
Test error - exited with non-zero exit code

### ISSUE THREAD

**Issue by VimacN** [sunbeam-labs/sunbeam#286]
Hi, 
I seem to have an error when running the test data on a Ubuntu 18 device.
After a successful installation I execute the test command "tests/run_tests.bash -e sunbeam" I get the following error:

`rbt: error while loading shared libraries: libblis.so.3: cannot open shared object file: No such file or directory
[Mon Feb 22 10:31:19 2021]
Error in rule remove_low_complexity:
    jobid: 41
    output: /tmp/tmp.AkZ4811wgz/sunbeam_output/qc/03_komplexity/dummyecoli_1.fastq.gz
    shell:
        
        gzip -dc /tmp/tmp.AkZ4811wgz/sunbeam_output/qc/02_trimmomatic/dummyecoli_1.fastq.gz | rbt fastq-filter /tmp/tmp.AkZ4811wgz/sunbeam_output/qc/log/komplexity/dummyecoli.filtered_ids |        gzip > /tmp/tmp.AkZ4811wgz/sunbeam_output/qc/03_komplexity/dummyecoli_1.fastq.gz
        
        (exited with non-zero exit code)

Removing output files of failed job remove_low_complexity since they might be corrupted:`

I include the log file for additional information.

Any ideas on how to proceed?

Thanks
[2021-02-22T103110.339519.snakemake.log](https://github.com/sunbeam-labs/sunbeam/files/6021591/2021-02-22T103110.339519.snakemake.log)

**Comment by yattaa** [comment]
Hi VimacN,

This appears to be due to a missing conda rbt dependency, potentially introduced in the latest miniconda release.  

Please try the following : $conda install -y -c conda-forge blas-devel

Hope that helps!

Cheers,
hatem

**Comment by ressy** [comment]
Thanks @yattaa for helping with this.  When I tried, blas-devel still didn't pull in blis automatically, so if anyone still has trouble with this you can also `conda install -y -c conda-forge blis`.  I just opened an issue with bioconda to try to get the rust-bio-tools package metadata updated: https://github.com/bioconda/bioconda-recipes/issues/27424

**Comment by yattaa** [comment]
You're welcome, glad I could help! Thank you for your excellent work and for opening that issue with bioconda. 🍻

**Comment by louiejtaylor** [comment]
For posterity (and so that I can check the status of this more easily in the future), I submitted a PR to the rbt recipe in bioconda to explicitly include blis: https://github.com/bioconda/bioconda-recipes/pull/27752

We should be safe to remove it from the Sunbeam env a little while after this PR goes through
