### ISSUE TITLE
 PROBLEM INSTALLING SUNBEAM

### ISSUE THREAD

**Issue by guianrey** [sunbeam-labs/sunbeam#299]
Hi, I don't know why I get this error when installing sunbeam?

![Sin título](https://user-images.githubusercontent.com/85709303/121598938-fe99b480-ca07-11eb-8a68-bd85a19b7998.jpg)

**Comment by Ulthran** [comment]
Hi @guianrey,

Looks like your issue is coming from `git` being unavailable in the current environment. This should be fixed in sunbeam3 as `git` is not included in the main env. Please try installing the latest stable version and open a new issue if the problem persists.

Thanks,
Charlie
