### ISSUE TITLE
tests failed on multiqc_report 

### ISSUE THREAD

**Issue by zoey-rw** [sunbeam-labs/sunbeam#300]
![image](https://user-images.githubusercontent.com/29359782/121791616-db166b80-cbb9-11eb-9efa-2f067c4f1011.png)

Tests failed at the multiqc_report step in run_tests.bash, running Sunbeam on the development branch. The log files didn't have additional information. Any ideas on how to proceed?

Thank you!

**Comment by Ulthran** [comment]
Hi @zoey-rw,

It's possible you got a version of the dev branch with a bug that would cause this test to fail. Or something might've gone wrong with the installation. Regardless please try reinstalling with the new stable branch and open a new issue if the problem persists.

Also running tests with the `-v` option will give a lot more debugging information. :)

Thanks,
Charlie
