### ISSUE TITLE
test_mapping test failed

### ISSUE THREAD

**Issue by quaeler** [sunbeam-labs/sunbeam#303]
Hi -

While running `tests/run_tests.bash -e sunbeam` as a part of initial installation instructions, i see:
```
...
Running test_guess_with_two_samples... ✔
Running test_mapping... 
Failed command error output:
Found extension sbx_test in folder sbx_test
Found extension sbx_test_subdir in folder sbx_test_subdir
Collecting host/contaminant genomes... done.
Collecting target genomes... done.
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	2	adapter_removal_paired
	2	aggregate_reads
	4	align_to_genome
	2	align_to_host
	1	all_mapping
	4	filter_reads
	2	find_low_complexity
	2	get_mapped_reads
	4	qc_final
	4	remove_low_complexity
	4	sample_intake
	4	samtools_convert
	4	samtools_get_coverage
	4	samtools_index
	4	samtools_mpileup
	2	samtools_summarize_coverage
	2	trimmomatic_paired
	51

...

[Sat Sep 11 09:58:27 2021]
localrule all_mapping:
    input: /tmp/tmp.6cwB4v2NA7/sunbeam_output/mapping/human/stub_human.bam.bai, /tmp/tmp.6cwB4v2NA7/sunbeam_output/mapping/human/stub2_human.bam.bai, /tmp/tmp.6cwB4v2NA7/sunbeam_output/mapping/phix174/stub_human.bam.bai, /tmp/tmp.6cwB4v2NA7/sunbeam_output/mapping/phix174/stub2_human.bam.bai, /tmp/tmp.6cwB4v2NA7/sunbeam_output/mapping/human/stub_human.raw.bcf, /tmp/tmp.6cwB4v2NA7/sunbeam_output/mapping/human/stub2_human.raw.bcf, /tmp/tmp.6cwB4v2NA7/sunbeam_output/mapping/phix174/stub_human.raw.bcf, /tmp/tmp.6cwB4v2NA7/sunbeam_output/mapping/phix174/stub2_human.raw.bcf, /tmp/tmp.6cwB4v2NA7/sunbeam_output/mapping/human/coverage.csv, /tmp/tmp.6cwB4v2NA7/sunbeam_output/mapping/phix174/coverage.csv
    jobid: 0

[Sat Sep 11 09:58:27 2021]
Finished job 0.
51 of 51 steps (100%) done
Complete log: /home/ec2-user/sunbeam-stable/.snakemake/log/2021-09-11T095812.799252.snakemake.log
x (log: /tmp/tmp.6cwB4v2NA7/test_mapping.[out/err])
-- TESTS FAILED --
```

Is this a known issue, and/or can someone suggest a way to triage this?

**Comment by AAMCgenomics** [comment]
I am seeing similar error:

Finished job 15.
49 of 51 steps (96%) done

[Wed May 18 19:33:47 2022]
rule samtools_summarize_coverage:
    input: /tmp/tmp.SGQigPF9h6/sunbeam_output/mapping/intermediates/phix174/stub2_human.csv, /tmp/tmp.SGQigPF9h6/sunbeam_output/mapping/intermediates/phix174/stub_human.csv
    output: /tmp/tmp.SGQigPF9h6/sunbeam_output/mapping/phix174/coverage.csv
    jobid: 9
    wildcards: genome=phix174

[Wed May 18 19:33:47 2022]
Finished job 9.
50 of 51 steps (98%) done

[Wed May 18 19:33:47 2022]
localrule all_mapping:
    input: /tmp/tmp.SGQigPF9h6/sunbeam_output/mapping/phix174/stub_human.bam.bai, /tmp/tmp.SGQigPF9h6/sunbeam_output/mapping/phix174/stub2_human.bam.bai, /tmp/tmp.SGQigPF9h6/sunbeam_output/mapping/human/stub_human.bam.bai, /tmp/tmp.SGQigPF9h6/sunbeam_output/mapping/human/stub2_human.bam.bai, /tmp/tmp.SGQigPF9h6/sunbeam_output/mapping/phix174/stub_human.raw.bcf, /tmp/tmp.SGQigPF9h6/sunbeam_output/mapping/phix174/stub2_human.raw.bcf, /tmp/tmp.SGQigPF9h6/sunbeam_output/mapping/human/stub_human.raw.bcf, /tmp/tmp.SGQigPF9h6/sunbeam_output/mapping/human/stub2_human.raw.bcf, /tmp/tmp.SGQigPF9h6/sunbeam_output/mapping/phix174/coverage.csv, /tmp/tmp.SGQigPF9h6/sunbeam_output/mapping/human/coverage.csv
    jobid: 0

[Wed May 18 19:33:47 2022]
Finished job 0.
51 of 51 steps (100%) done
Complete log: /home/jovyan/sunbeam-stable/.snakemake/log/2022-05-18T193324.846318.snakemake.log

Do you find how to overcome it?

**Comment by Ulthran** [comment]
Hi @quaeler & @AAMCgenomics,

Unfortunately this seems to be a fairly common issue with sunbeam version <3 (#284 & #295). I haven't been able to replicate it with sunbeam3 (and haven't seen any issues arise) so I'm hoping this is fixed in the latest version. Please try reinstalling with the latest stable branch and open a new issue if the problem persists.

Thanks,
Charlie
