### ISSUE TITLE
sunbeam init doesn't produce the config file if .placeholder is in the extensions folder

### ISSUE THREAD

**Issue by ctanes** [sunbeam-labs/sunbeam#306]
Hello! I have recently upgraded to the dev branch. Not a big issue, but after I copied over all the sbx folders to the extensions folder, the sunbeam init failed at creating the config file. I could resolve this by removing the .placeholder file in the extensions folder.

**Comment by Ulthran** [comment]
Can this issue be closed? This should work in sunbeam3 (other than that one version where I broke it).
