### ISSUE TITLE
Roadmap for future development

### ISSUE THREAD

**Issue by eclarke** [sunbeam-labs/sunbeam#33]
Soliciting comments from @kylebittinger and @zhaoc1 

We have bare-bones functional testing up and working right now. I would like to get things a little bit more formal for future development, since we now have active users and we need to worry about things breaking during our updates.

Highest priority:

- No absolute paths or references to our particular development environment (usernames, paths, etc) should be committed to the repository.
- All bash scripts must have `set -e` enabled and they should not be committed if it is missing or commented out.
- Python code must be indented with spaces, not tabs. I don't really care either way, but it has to be consistent across our codebase, so I'm just picking the side most used currently.
- Nothing will be merged to `master` unless it passes functional testing on Travis. 
- All non-trivial code should be refactored into a function that goes into the `sunbeam/sunbeam` package. We should test this using a service like [Landscape](https://landscape.io) to ensure code correctness and well-formattedness.

Architectural changes:

- Versioning and release system. I want to follow [semantic versioning](http://semver.org) practices for this project.
- We need a defined final number of artifacts (annotations, contigs, qc, and read classifications) with a defined folder hierarchy. This will be what's tested and what defines our "API", so to speak. Changes to this will require a bump in the version number.

**Comment by kylebittinger** [comment]
Erik,

I agree with the policies you've laid out.  The Landscape and Travis tools look useful.  In addition to the  policies you listed, another thing to watch is that new tests don't leave temp files lying around.

Let's focus on getting good code style and good tests over the next several pull requests.  The ideal situation is to make a new issue, create a branch to fix the issue, commit a new, working test along with the changes, and have a detailed code review when the pull request comes in.

**Comment by eclarke** [comment]
These are implemented so I'm closing the issue
