### ISSUE TITLE
Snakelike thinks symptomatic links are code changes for large files

### ISSUE THREAD

**Issue by ctanes** [sunbeam-labs/sunbeam#330]
For large files (order of gigabytes), after a first pass of processing is done, snakelike thinks the symptoms links form the sample intake rules are code changes and wants to run the pipeline all over again. I didn't see this issue in smaller files.

**Comment by Ulthran** [comment]
This seems to be an issue in snakemake 7.8 that doesn't appear in earlier versions (for us, 7.3.3 worked). However there are also issues with versions <7.8 (#343) being not able to find inputs on cluster runs (maybe an issue with the number of inputs?). Testing with latest version 7.15.1 to see if it might solve both issues.

**Comment by Ulthran** [comment]
Snakemake 7.15.1 seems to work, closing with #343.
