### ISSUE TITLE
how to get some common sequence from different samples for the table?

### ISSUE THREAD

**Issue by luozhy88** [sunbeam-labs/sunbeam#341]
I used the sunbeam,but I have a problem about the result.I want to get some common sequence from different samples for the table. How?

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/94740863/189239933-c4206c5b-ab61-46cf-82db-47587cd50c83.png">

**Comment by Ulthran** [comment]
Hi luozhy88,

I'm a little confused by the question. Are you looking for which OTUs are showing up across your samples? If so, I think that falls outside the scope of sunbeam and into the realm of processing outputs. I'd suggest a simple script to run through the tsv.

Thanks,
Charlie

**Comment by Ulthran** [comment]
Hi @luozhy88, I'm going to close this for inactivity. I think it might also be beyond the scope of sunbeam itself and have to do more with analysis of the outputs. If you have anything to add or revise either do that here or open a new issue.
