### ISSUE TITLE
Consider using third-party tools to filter BAM files and extract unmapped reads

### ISSUE THREAD

**Issue by kylebittinger** [sunbeam-labs/sunbeam#363]
Right now, we use some custom Python code to filter and remove reads aligning to the host genome. However, we might easily accomplish the same task using third-party tools.

Rather than setting a percent identity and alignment length in the config (which by default are set pretty low), we might simply set the minimum alignment score in `bwa`. And to extract unmapped reads, we might use any of the BAM/SAM-to-FASTQ utilities that are available. As a downside, I wonder if we would lose valuable info in the FASTQ headers this way.

**Comment by Ulthran** [comment]
Not sure why this didn't close with merged PR
