### ISSUE TITLE
run_tests.sh fails at the "Running test_all... " step - Missing output files

### ISSUE THREAD

**Issue by TakacsBertalan** [sunbeam-labs/sunbeam#370]
Hi!

I have a problem testing my Sunbeam installation. Running the run_tests.sh scripts results in the following error
```
Running setup... ✔
Running build_test_data... ✔
Running test_all... 
Failed command error output:
Check failed on sunbeam_output/annotation/summary/dummyecoli.tsv
x (log: /tmp/tmp.ma2qF2MGb3/test_all.[out/err])
-- TESTS FAILED --
```
I am enclosing the complete log file. It seems like the "Missing output files" and "Input files updated by another job:" messages show up constantly, maybe that could be the root of the problem?
[2022-12-21T105322.886319.snakemake.log](https://github.com/sunbeam-labs/sunbeam/files/10276708/2022-12-21T105322.886319.snakemake.log)

**Comment by Ulthran** [comment]
Hi @TakacsBertalan,

Could you please specify what version of sunbeam you're running (from the sunbeam directory, you can copy the output of `git status`)?

Also, can you copy the command that you're using to run the tests here as well?

Thanks,
Charlie

**Comment by TakacsBertalan** [comment]
Hi Charlie,

I am using sunbeam v3.1.1. Git status says
`On branch stable
Your branch is up to date with 'origin/stable'.`

The command I use: `./tests/run_tests.sh -e sunbeam3.1.1` from my sunbeam directory. The sunbeam3.1.1 is the environment where I installed sunbeam, it is activated when I run the script.

Thanks,
Bertalan

**Comment by Ulthran** [comment]
Great thanks Bertalan. I'd suggest running `bash tests/run_tests.sh -e sunbeam3.1.1 -d tmp_out/ -v` to get verbose output and keep all the output in the `tmp_out/` directory. If the problem isn't apparent from that, please post the full log from that run and the structure of `tmp_out/` (using something like `tree tmp_out`).

 - Charlie

**Comment by TakacsBertalan** [comment]
Hi!
After trying to solve the problem unsuccessfully, I deleted the whole environment and installed Sunbeam again. Running the test resulted in a different error this time, I could not reproduce this one. I will open a new issue for the new error. https://github.com/sunbeam-labs/sunbeam/issues/386
