### ISSUE TITLE
Tests failing on new installation: module 'contextlib' has no attribute 'asynccontextmanager'

### ISSUE THREAD

**Issue by mvee18** [sunbeam-labs/sunbeam#393]
Hello,

I recently tried to install sunbeam using the methods provided in https://sunbeam.readthedocs.io/en/stable/quickstart.html and it seems to have successfully installed. However, running the test suite leads to the following failure (the full test output is attached):

```
AttributeError: module 'contextlib' has no attribute 'asynccontextmanager'                                                                                                                                               
```

[tests.log](https://github.com/sunbeam-labs/sunbeam/files/10970717/tests.log)

Oddly enough, the following seems to work:

```
$ python
>>> from contextlib import asynccontextmanager
```

Thanks for looking into this.

**Comment by Ulthran** [comment]
Hi @mvee18 , thanks for the issue report. I was actually just working on a very similar issue in a totally different place so I think I know what's going on :). Looking through the log you provided this appears to be the first error to pop up:

```
Activating conda environment: ../../../gpfs/gsfs12/users/TBHD_share/SUNBEAM/.snakemake/1fe7460c9d3c6ddba6ee4fb5e1cd91f3_
python -c "import sys; print(f'3.11')"
```

This very uninformative error basically always means that you're dealing with incompatible versions of python, which is unfortunately a struggle when using multiple environments. You can confirm this by running:

```
conda activate sunbeam
python --version
conda activate $SUNBEAM_DIR/.snakemake/1fe7460c9d3c6ddba6ee4fb5e1cd91f3_
python --version
```

I'm guessing that one of these will be python 2 and the other python 3 (probably the first is 3 and the second 2 actually). If this is the case, you can fix it by specifying `python>3` in the qc env by adding ` - python>3` to the bottom of `envs/qc.yml`. Unfortunately the qc env in particular is very fragile in sunbeam 3 so this might well cause more problems.

If it does, sunbeam 4 is on the verge of release now where there should be significantly less issues with bulky environments.

 - Charlie

**Comment by mvee18** [comment]
Hey Charlie,

I had success getting sunbeam to run by cloning the dev branch as opposed to the stable branch. I am not sure what is causing the issue in the stable branch, but this has fixed my problems for now.

**Comment by Ulthran** [comment]
Hi @mvee18 ,

Sorry for the slow reply. We just put out a pre-release of v4 ([v4.0.0-rc.1](https://github.com/sunbeam-labs/sunbeam/releases/tag/v4.0.0-rc.1)) that should be pretty much equivalent to the dev branch you cloned. The sunbeam CLI has changed as have the tests. If you have any questions, comments, feedback please let me know.

Thanks,
Charlie
