### ISSUE TITLE
KeyError in file sbx_coassembly.smk

### ISSUE THREAD

**Issue by benyoung93** [sunbeam-labs/sunbeam#398]
good afternoon :) 

First of all, thank you for this snakemake, its made my life alot easier for processing some metag samples asap. 

I have run `bash tests/run_tests.bash ` and everything seems to be all good up to the test old illumina 

```
Running setup... ✔
Running build_test_data... ✔
Running test_all... ✔
Running test_all_old_illumina... ✔
```

Unfortunately, the extension test yields the following output 

```
Running test_all_sunbeam_extend... 
Failed command error output:
Installing sbx_coassembly from https://github.com/sunbeam-labs/sbx_coassembly
Found extension sbx_test in folder sbx_test
Found extension sbx_test_subdir in folder sbx_test_subdir
Found extension sbx_test_smk in folder sbx_test_smk
Found extension sbx_coassembly in folder sbx_coassembly
Collecting host/contaminant genomes... done.
Collecting target genomes... done.
KeyError in file /nethome/bdy8/programs/sunbeam/extensions/sbx_coassembly/sbx_coassembly.smk, line 8:
'benchmarks'
  File "/nethome/bdy8/programs/sunbeam/Snakefile", line 141, in <module>
  File "/nethome/bdy8/programs/sunbeam/extensions/sbx_coassembly/sbx_coassembly.smk", line 8, in <module>
  File "/nethome/bdy8/programs/sunbeam/sunbeamlib/config.py", line 73, in output_subdir
x (log: /tmp/tmp.gpyeVMeB36/test_all_sunbeam_extend.[out/err])
-- TESTS FAILED --
```

I am able to progress with what I am doing, as I think this is an extension for something else (?). Apologies a bit of a noob. I did `cd` into the extensions folder  (`nethome/bdy8/programs/sunbeam/extensions`) and theres is nothing in there, so could that be the problem?

Sunbeam version - sunbeam v3.1.1

This is running on a hpc cluster as well. 

Thank you :) 

Ben

**Comment by Ulthran** [comment]
Hi @benyoung93,

Thanks for the bug report. This looks like something I messed up on while updating extensions for sunbeam v4 while remaining backwards compatible. I just pushed changes to that extension that should make the test work properly.

You're also welcome to try out v4 (currently on the `dev` branch, `git checkout dev`) if you run into other problems with 3.1.1. It's still technically a pre-release but should work well and cut down on a lot of the complexity of 3.1.1. Lots of functionality was moved from the main pipeline to [extensions](https://github.com/sunbeam-labs/), in case you wonder where some of the components went.

**Comment by benyoung93** [comment]
Good morning @Ulthran 

Thank you for the quick response, I will have a go at that after my run has completed :). 

I will definitely update to V4 when I am processing the 200 samples that I will have, this is just a wee prelim trial with 6 samples so rather than mess things up Ill let v3.1.1 go for now :)

When will v4 be released just out of curiosity?

Ben

**Comment by Ulthran** [comment]
Right now it's in the process of being run/tested in-house until it's performed satisfactorily on a number of projects so it's subject to how long that takes. Aiming for within a few weeks probably.

**Comment by benyoung93** [comment]
that timeline re v4 sounds perfect for my large dataset. Thank you so much for the quick responses and have a wonderful week :).
