### ISSUE TITLE
Error in rule kraken2_classify_report:

### ISSUE THREAD

**Issue by mabouelk** [sunbeam-labs/sunbeam#402]
Error in rule kraken2_classify_report:
    jobid: 16
    input: /home/exouser/Desktop/CDV/sunbeam_output/qc/decontam/CDV1_S1_L001_1.fastq.gz, /home/exouser/Desktop/CDV/sunbeam_output/qc/decontam/CDV1_S1_L001_2.fastq.gz
    output: /home/exouser/Desktop/CDV/sunbeam_output/classify/kraken/raw/CDV1_S1_L001-raw.tsv, /home/exouser/Desktop/CDV/sunbeam_output/classify/kraken/CDV1_S1_L001-taxa.tsv
    shell:
        
        kraken2 --gzip-compressed                 --db /home/exouser/Desktop/CDV                 --report /home/exouser/Desktop/CDV/sunbeam_output/classify/kraken/CDV1_S1_L001-taxa.tsv                 --paired /home/exouser/Desktop/CDV/sunbeam_output/qc/decontam/CDV1_S1_L001_1.fastq.gz /home/exouser/Desktop/CDV/sunbeam_output/qc/decontam/CDV1_S1_L001_2.fastq.gz                 > /home/exouser/Desktop/CDV/sunbeam_output/classify/kraken/raw/CDV1_S1_L001-raw.tsv
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job kraken2_classify_report since they might be corrupted:
/home/exouser/Desktop/CDV/sunbeam_output/classify/kraken/raw/CDV1_S1_L001-raw.tsv
Environment defines Python version < 3.7. Using Python of the main process to execute script. Note that this cannot be avoided, because the script uses data structures from Snakemake which are Python >=3.7 only.

**Comment by Ulthran** [comment]
Hi @mabouelk, I actually ran into this recently in my own usage of sunbeam and the fix is now included in the version 4 release. I'd recommend installing the newest release.
