### ISSUE TITLE
test_mapping frozen

### ISSUE THREAD

**Issue by rpalcab** [sunbeam-labs/sunbeam#404]
Hi!
I'm running the recommended tests after installing Sunbeam v3.1.1. I've tried it two times, always getting stuck at `Running test_mapping...`, where the execution apparently freezes (for more than 24h). I had to manually cancel the execution.

When I've checked the log files (test_mapping.out and test_mapping.err), I get the following results:
```
test_mapping.out
Running: snakemake --snakefile /home/laura/sunbeam/Snakefile -c --use-conda --conda-prefix /home/laura/sunbeam/.snakemake all_mapping --configfile /tmp/tmp.s3tK5DkQSS/test_mapping_config.yml
```

```
test_mapping.err
Unexpected coverage.csv content from mapping rules

exit
```

This is the content of the different coverage.csv files:
```
sunbeam_output/mapping/human_copy/coverage.csv
Genome,Segment,Sample,Min,Max,Mean,Median,Std Dev,Segment Coverage,Segment Length
human_copy,KI270762.2,stub2_human,0,2,0.001,0.0,0.04471017781221633,40,80000
human_copy,KI270762.2,stub_human,0,2,0.002,0.0,0.06321392251711641,80,80000
```

```
sunbeam_output/mapping/human/coverage.csv
Genome,Segment,Sample,Min,Max,Mean,Median,Std Dev,Segment Coverage,Segment Length
human,KI270762.1,stub2_human,0,2,0.001,0.0,0.04471017781221633,40,80000
human,KI270762.1,stub_human,0,2,0.002,0.0,0.06321392251711641,80,80000
```

```
sunbeam_output/mapping/phix174/coverage.csv
Genome,Segment,Sample,Min,Max,Mean,Median,Std Dev,Segment Coverage,Segment Length
```

```
sunbeam_output_old_illumina/mapping/human_copy/coverage.csv
Genome,Segment,Sample,Min,Max,Mean,Median,Std Dev,Segment Coverage,Segment Length
```

```
sunbeam_output_old_illumina/mapping/human/coverage.csv
Genome,Segment,Sample,Min,Max,Mean,Median,Std Dev,Segment Coverage,Segment Length
```

```
sunbeam_output_old_illumina/mapping/phix174/coverage.csv
Genome,Segment,Sample,Min,Max,Mean,Median,Std Dev,Segment Coverage,Segment Length
```

I'd appreciate any comments or suggestions on what could be going wrong and how to solve it.

Thanks!

**Comment by Ulthran** [comment]
Hi @rpalcab , thanks for using sunbeam! I'd recommend using version 4 (which we just released) as it fixes a lot of these issues that sunbeam 3 had with tests going wrong on install. If you have any questions on the new features you can find the answers in the docs [here](https://sunbeam.readthedocs.io/en/stable/index.html) and if anything doesn't seem to be working please open up a new issue.
