### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by KilKa9** [sunbeam-labs/sunbeam#415]
Hello,

Installation failed when installing Sunbeam library : " ERROR: Failed building wheel for sunbeam "
It seems that setuptools.installer and fetch_build_eggs are deprecated

![Screenshot from 2023-09-25 10-23-58](https://github.com/sunbeam-labs/sunbeam/assets/24605269/eecce196-1b18-4806-95b9-60ade7c9f9ea)

**Sunbeam version**
v4.0.0
Ubuntu 22.04.3 LTS

If you could help me find out what's wrong.
Thank you.

**Comment by Ulthran** [comment]
Hi @KilKa9, thanks for using sunbeam! Updating the sunbeamlib setup has been on my list for a while, I'll hopefully include this in the next release.

For a quick fix, you can try the following:

```bash
conda activate sunbeam4.0.0
cd /home/virologie/sunbeam/
pip install .
```

If that gives you the same deprecation error then try running `pip install --use-pep517 .`. If that works you should be able to use sunbeam as normal.

Please let me know if that helps or not.

Charlie

**Comment by KilKa9** [comment]
Hi,
Thank you for your answer.
Unfortunately, it didn't work, I get the same error message.

**Comment by KilKa9** [comment]
Hi, 
Downgrading conda to version 23.7.4 has solved the library issue. 

Thank you for your help

**Comment by Ulthran** [comment]
Great! Thanks for finding a work around for this. I've got a PR in progress to update to pyproject.toml and make some related changes. Hopefully this will help anyone who runs into a similar issue until that's released.
