### ISSUE TITLE
How to provide empty cutadapt_opts?

### ISSUE THREAD

**Issue by levlitichev** [sunbeam-labs/sunbeam#427]
Hi Charlie,

Me again.

I don't want to provide `--discard-trimmed` as an option to cutadapt. If I instead provide an empty string (or a string with a space) in the config, I get the following error:

```
Run "cutadapt --help" to see command-line options.
See https://cutadapt.readthedocs.io/ for full documentation.

cutadapt: error: unrecognized arguments: </path/to/first.fastq.gz> </path/to/second.fastq.gz> 
```

Any recommendations for what to provide instead to the `cutadapt_opts` parameter in the config?

The code works fine if I don't modify this parameter in the config. I'm using version 4.0.0.

Thanks,
Lev

**Comment by Ulthran** [comment]
Hi Lev, sorry about that, it's a bug in the adapter_removal script. #428 should fix it, just merged into main.

**Comment by levlitichev** [comment]
Nice! Thank you for the really quick turnaround.
