### ISSUE TITLE
Intermediate files in assembly (IDBA-UD)

### ISSUE THREAD

**Issue by varunaggarwala** [sunbeam-labs/sunbeam#65]
Can the end user request for saving the intermediate files in the assembly step (IDBA_UD). These intermediate files can aid in finding reads that are mapped to contigs (or not) and can be valuable for downstream processing.

**Comment by eclarke** [comment]
Sorry for the long delay. We're going to address this in the next version.

**Comment by eclarke** [comment]
We use a new assembler and keep the intermediate files. We also don't use a greedy final assembler like CAP3 so it's easier to interpret the final contigs.
