### ISSUE TITLE
Snakemake version compatibility ('Namedlist' object has no attribute 'readline')

### ISSUE THREAD

**Issue by louiejtaylor** [sunbeam-labs/sunbeam#77]
Compatibility issue with snakemake version 3.13.2, workaroung by forcing 3.13.0 (`conda install snakemake=3.13.0`)

Top-level traceback:
Error in job parse_genes_mga while creating [output files]
RuleException:
AttributeError in line 39 of ~/sunbeam/rules/annotation/orf.rules:
'Namedlist' object has no attribute 'readline'

**Comment by ressy** [comment]
Yeah, we just included snakemake=3.13.0 explicitly in Sunbeam's requirements.txt yesterday (in #75) to make it work for the time being, but come to think of it, there should probably be an open issue anyway to deal with actually fixing that compatibility problem.  Thanks Louis.
