### ISSUE TITLE
Support mapping of reads to assembled contigs

### ISSUE THREAD

**Issue by ressy** [sunbeam-labs/sunbeam#81]
Right now the mapping rules only align to a set of existing fasta files provided as input to Sunbeam.  It would be useful to also allow the mapping of reads to the contigs created by the assembly section.  We should add this as a new feature in the mapping section.

**Comment by eclarke** [comment]
Do you think we could accomplish this by having users set the `mapping:genomes_fp` config option to point to the assembled contigs?

**Comment by zhaoc1** [comment]
I implemented contigs.rules in our neutrino (https://github.com/PennChopMicrobiomeProgram/sunbeam_neutrino/blob/master/rules/mapping/contigs.rules). And what I did is to have a json file: {sample1: {contigs}}

**Comment by ressy** [comment]
@zhaoc1 this is what you added back in the fall as `assembly/coverage.rules`, right?  (So is this one already finished?)

**Comment by ressy** [comment]
Great, thanks!
